//
// This file is autogenerated.
// Edit `data/hpdf_page_sizes.template` and `data/hpdf_page_sizes.json` instead.
//

/*
 * << Haru Free PDF Library >> -- hpdf_page_sizes.h
 *
 * URL: http://libharu.org
 *
 * Copyright (c) 1999-2006 Takeshi Kanno <takeshi_kanno@est.hi-ho.ne.jp>
 * Copyright (c) 2007-2009 Antony Dovgal <tony@daylessday.org>
 * Copyright (c) 2023 Dmitry Solomennikov
 *
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.
 * It is provided "as is" without express or implied warranty.
 *
 */

#ifndef _HPDF_PAGE_SIZES_H
#define _HPDF_PAGE_SIZES_H

#ifdef __cplusplus
extern "C" {
#endif

/**
  \ingroup page
  \brief Data structure representing page size (width and height), in points.
*/
typedef struct _HPDF_PageSizeValue {
    HPDF_REAL   x;
    HPDF_REAL   y;
} HPDF_PageSizeValue;

/**
  List of predefined page sizes.

  Data gathered from wonderful site <a href="https://papersizes.io/">https://papersizes.io/</a>

  \image html img/papersizes_logo_small.png

  Known page sizes include:
  - International
  - US
  - US envelope
  - International envelope
  - Photography
  - Newspapers
  - Books
  - Business card
  - Raw
  - Billboard
  - Russian
  - French
  - Japanese
  - Canadian
  - German
  - Swedish
  - Colombian
  - Chinese
  - Traditional British
  - Imperial
  - Transitional

  Sizes are given in millimeters and converted to points.
*/
typedef enum _HPDF_PageSizes {
    /// US Loose "Letter" page size (216.0mm x 279.0mm)
    HPDF_PAGE_SIZE_US_LETTER = 0,
    /// US Loose "Legal" page size (216.0mm x 356.0mm)
    HPDF_PAGE_SIZE_US_LEGAL,
    /// US Loose "Tabloid" page size (279.0mm x 432.0mm)
    HPDF_PAGE_SIZE_US_TABLOID,
    /// US Loose "Ledger" page size (432.0mm x 279.0mm)
    HPDF_PAGE_SIZE_US_LEDGER,
    /// US Loose "Junior Legal" page size (127.0mm x 203.0mm)
    HPDF_PAGE_SIZE_US_JUNIOR_LEGAL,
    /// US Loose "Half Letter" page size (140.0mm x 216.0mm)
    HPDF_PAGE_SIZE_US_HALF_LETTER,
    /// US Loose "Government Letter" page size (203.0mm x 267.0mm)
    HPDF_PAGE_SIZE_US_GOVERNMENT_LETTER,
    /// US Loose "Government Legal" page size (216.0mm x 330.0mm)
    HPDF_PAGE_SIZE_US_GOVERNMENT_LEGAL,

    /// US ANSI "ANSI A" page size (216.0mm x 279.0mm)
    HPDF_PAGE_SIZE_US_ANSI_A,
    /// US ANSI "ANSI B" page size (279.0mm x 432.0mm)
    HPDF_PAGE_SIZE_US_ANSI_B,
    /// US ANSI "ANSI C" page size (432.0mm x 559.0mm)
    HPDF_PAGE_SIZE_US_ANSI_C,
    /// US ANSI "ANSI D" page size (559.0mm x 864.0mm)
    HPDF_PAGE_SIZE_US_ANSI_D,
    /// US ANSI "ANSI E" page size (864.0mm x 1118.0mm)
    HPDF_PAGE_SIZE_US_ANSI_E,

    /// US Arch "Arch A" page size (229.0mm x 305.0mm)
    HPDF_PAGE_SIZE_US_ARCH_A,
    /// US Arch "Arch B" page size (305.0mm x 457.0mm)
    HPDF_PAGE_SIZE_US_ARCH_B,
    /// US Arch "Arch C" page size (457.0mm x 610.0mm)
    HPDF_PAGE_SIZE_US_ARCH_C,
    /// US Arch "Arch D" page size (610.0mm x 914.0mm)
    HPDF_PAGE_SIZE_US_ARCH_D,
    /// US Arch "Arch E" page size (914.0mm x 1219.0mm)
    HPDF_PAGE_SIZE_US_ARCH_E,
    /// US Arch "Arch E1" page size (762.0mm x 1067.0mm)
    HPDF_PAGE_SIZE_US_ARCH_E1,
    /// US Arch "Arch E2" page size (660.0mm x 965.0mm)
    HPDF_PAGE_SIZE_US_ARCH_E2,
    /// US Arch "Arch E3" page size (686.0mm x 991.0mm)
    HPDF_PAGE_SIZE_US_ARCH_E3,

    /// ISO 216 "4A0" page size (1682.0mm x 2378.0mm)
    HPDF_PAGE_SIZE_4A0,
    /// ISO 216 "2A0" page size (1189.0mm x 1682.0mm)
    HPDF_PAGE_SIZE_2A0,
    /// ISO 216 "A0" page size (841.0mm x 1189.0mm)
    HPDF_PAGE_SIZE_A0,
    /// ISO 216 "A0+" page size (914.0mm x 1292.0mm)
    HPDF_PAGE_SIZE_A0_PLUS,
    /// ISO 216 "A1" page size (594.0mm x 841.0mm)
    HPDF_PAGE_SIZE_A1,
    /// ISO 216 "A1+" page size (609.0mm x 914.0mm)
    HPDF_PAGE_SIZE_A1_PLUS,
    /// ISO 216 "A2" page size (420.0mm x 594.0mm)
    HPDF_PAGE_SIZE_A2,
    /// ISO 216 "A3" page size (297.0mm x 420.0mm)
    HPDF_PAGE_SIZE_A3,
    /// ISO 216 "A3+" page size (329.0mm x 483.0mm)
    HPDF_PAGE_SIZE_A3_PLUS,
    /// ISO 216 "A4" page size (210.0mm x 297.0mm)
    HPDF_PAGE_SIZE_A4,
    /// ISO 216 "A5" page size (148.0mm x 210.0mm)
    HPDF_PAGE_SIZE_A5,
    /// ISO 216 "A6" page size (105.0mm x 148.0mm)
    HPDF_PAGE_SIZE_A6,
    /// ISO 216 "A7" page size (74.0mm x 105.0mm)
    HPDF_PAGE_SIZE_A7,
    /// ISO 216 "A8" page size (52.0mm x 74.0mm)
    HPDF_PAGE_SIZE_A8,
    /// ISO 216 "A9" page size (37.0mm x 52.0mm)
    HPDF_PAGE_SIZE_A9,
    /// ISO 216 "A10" page size (26.0mm x 37.0mm)
    HPDF_PAGE_SIZE_A10,
    /// ISO 216 "B0" page size (1000.0mm x 1414.0mm)
    HPDF_PAGE_SIZE_B0,
    /// ISO 216 "B0+" page size (1118.0mm x 1580.0mm)
    HPDF_PAGE_SIZE_B0_PLUS,
    /// ISO 216 "B1" page size (707.0mm x 1000.0mm)
    HPDF_PAGE_SIZE_B1,
    /// ISO 216 "B1+" page size (720.0mm x 1020.0mm)
    HPDF_PAGE_SIZE_B1_PLUS,
    /// ISO 216 "B2" page size (500.0mm x 707.0mm)
    HPDF_PAGE_SIZE_B2,
    /// ISO 216 "B2+" page size (520.0mm x 720.0mm)
    HPDF_PAGE_SIZE_B2_PLUS,
    /// ISO 216 "B3" page size (353.0mm x 500.0mm)
    HPDF_PAGE_SIZE_B3,
    /// ISO 216 "B4" page size (250.0mm x 353.0mm)
    HPDF_PAGE_SIZE_B4,
    /// ISO 216 "B5" page size (176.0mm x 250.0mm)
    HPDF_PAGE_SIZE_B5,
    /// ISO 216 "B6" page size (125.0mm x 176.0mm)
    HPDF_PAGE_SIZE_B6,
    /// ISO 216 "B7" page size (88.0mm x 125.0mm)
    HPDF_PAGE_SIZE_B7,
    /// ISO 216 "B8" page size (62.0mm x 88.0mm)
    HPDF_PAGE_SIZE_B8,
    /// ISO 216 "B9" page size (44.0mm x 62.0mm)
    HPDF_PAGE_SIZE_B9,
    /// ISO 216 "B10" page size (31.0mm x 44.0mm)
    HPDF_PAGE_SIZE_B10,
    /// ISO 216 "B11" page size (22.0mm x 31.0mm)
    HPDF_PAGE_SIZE_B11,
    /// ISO 216 "B12" page size (15.0mm x 22.0mm)
    HPDF_PAGE_SIZE_B12,
    /// ISO 216 "B13" page size (11.0mm x 15.0mm)
    HPDF_PAGE_SIZE_B13,
    /// ISO 216 "C0" page size (917.0mm x 1297.0mm)
    HPDF_PAGE_SIZE_C0,
    /// ISO 216 "C1" page size (648.0mm x 917.0mm)
    HPDF_PAGE_SIZE_C1,
    /// ISO 216 "C2" page size (458.0mm x 648.0mm)
    HPDF_PAGE_SIZE_C2,
    /// ISO 216 "C3" page size (324.0mm x 458.0mm)
    HPDF_PAGE_SIZE_C3,
    /// ISO 216 "C4" page size (229.0mm x 324.0mm)
    HPDF_PAGE_SIZE_C4,
    /// ISO 216 "C5" page size (162.0mm x 229.0mm)
    HPDF_PAGE_SIZE_C5,
    /// ISO 216 "C6" page size (114.0mm x 162.0mm)
    HPDF_PAGE_SIZE_C6,
    /// ISO 216 "C7" page size (81.0mm x 114.0mm)
    HPDF_PAGE_SIZE_C7,
    /// ISO 216 "C8" page size (57.0mm x 81.0mm)
    HPDF_PAGE_SIZE_C8,
    /// ISO 216 "C9" page size (40.0mm x 57.0mm)
    HPDF_PAGE_SIZE_C9,
    /// ISO 216 "C10" page size (28.0mm x 40.0mm)
    HPDF_PAGE_SIZE_C10,

    /// Traditional British "Dukes" page size (140.0mm x 178.0mm)
    HPDF_PAGE_SIZE_BRITISH_DUKES,
    /// Traditional British "Foolscap" page size (203.0mm x 330.0mm)
    HPDF_PAGE_SIZE_BRITISH_FOOLSCAP,
    /// Traditional British "Imperial" page size (178.0mm x 229.0mm)
    HPDF_PAGE_SIZE_BRITISH_IMPERIAL,
    /// Traditional British "Kings" page size (165.0mm x 203.0mm)
    HPDF_PAGE_SIZE_BRITISH_KINGS,
    /// Traditional British "Quarto" page size (203.0mm x 254.0mm)
    HPDF_PAGE_SIZE_BRITISH_QUARTO,

    /// US Commercial envelopes "6¼" page size (152.0mm x 89.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_6_1_4,
    /// US Commercial envelopes "6¾" page size (165.0mm x 92.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_6_3_4,
    /// US Commercial envelopes "7" page size (172.0mm x 95.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_7,
    /// US Commercial envelopes "7¾ Monarch" page size (191.0mm x 98.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_7_3_4_MONARCH,
    /// US Commercial envelopes "8⅝ " page size (219.0mm x 92.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE8_5_8,
    /// US Commercial envelopes "9" page size (225.0mm x 98.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_9,
    /// US Commercial envelopes "10" page size (241.0mm x 104.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_10,
    /// US Commercial envelopes "11" page size (264.0mm x 114.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_11,
    /// US Commercial envelopes "12" page size (279.0mm x 121.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_12,
    /// US Commercial envelopes "14" page size (292.0mm x 127.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_14,
    /// US Commercial envelopes "16" page size (305.0mm x 152.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_16,

    /// US Announcement envelopes "A1" page size (92.0mm x 130.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_A1,
    /// US Announcement envelopes "A2 Lady Grey" page size (146.0mm x 111.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_A2_LADY_GREY,
    /// US Announcement envelopes "A4" page size (159.0mm x 108.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_A4,
    /// US Announcement envelopes "A6 Thompson's Standard" page size (165.0mm x 121.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_A6_THOMPSON_S_STANDARD,
    /// US Announcement envelopes "A7 Besselheim" page size (184.0mm x 133.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_A7_BESSELHEIM,
    /// US Announcement envelopes "A8 Carr's" page size (206.0mm x 140.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_A8_CARR_S,
    /// US Announcement envelopes "A9 Diplomat" page size (222.0mm x 146.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_A9_DIPLOMAT,
    /// US Announcement envelopes "A10 Willow" page size (241.0mm x 152.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_A10_WILLOW,
    /// US Announcement envelopes "A Long" page size (225.0mm x 98.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_A_LONG,

    /// US Catalog envelopes "1" page size (229.0mm x 152.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_1,
    /// US Catalog envelopes "1¾" page size (241.0mm x 152.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_1_3_4,
    /// US Catalog envelopes "3" page size (254.0mm x 178.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_3,
    /// US Catalog envelopes "6" page size (267.0mm x 191.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_6,
    /// US Catalog envelopes "8" page size (286.0mm x 210.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_8,
    /// US Catalog envelopes "9¾" page size (286.0mm x 222.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_9_3_4,
    /// US Catalog envelopes "10½" page size (305.0mm x 229.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_10_1_2,
    /// US Catalog envelopes "12½" page size (318.0mm x 241.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_12_1_2,
    /// US Catalog envelopes "13½" page size (330.0mm x 254.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_13_1_2,
    /// US Catalog envelopes "14½" page size (368.0mm x 292.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_14_1_2,
    /// US Catalog envelopes "15" page size (381.0mm x 254.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_15,
    /// US Catalog envelopes "15½" page size (394.0mm x 305.0mm)
    HPDF_PAGE_SIZE_US_ENVELOPE_15_1_2,

    /// ISO 269 "DL" page size (110.0mm x 220.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_DL,
    /// ISO 269 "B4" page size (250.0mm x 353.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_B4,
    /// ISO 269 "B5" page size (176.0mm x 250.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_B5,
    /// ISO 269 "B6" page size (125.0mm x 176.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_B6,
    /// ISO 269 "C3" page size (324.0mm x 458.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_C3,
    /// ISO 269 "C4" page size (229.0mm x 324.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_C4,
    /// ISO 269 "C4M" page size (318.0mm x 229.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_C4M,
    /// ISO 269 "C5" page size (162.0mm x 229.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_C5,
    /// ISO 269 "C6/C5" page size (114.0mm x 229.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_C6_C5,
    /// ISO 269 "C6" page size (114.0mm x 162.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_C6,
    /// ISO 269 "C64M" page size (318.0mm x 114.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_C64M,
    /// ISO 269 "C7/C6" page size (81.0mm x 162.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_C7_C6,
    /// ISO 269 "C7" page size (81.0mm x 114.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_C7,
    /// ISO 269 "CE4" page size (229.0mm x 310.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_CE4,
    /// ISO 269 "CE64" page size (114.0mm x 310.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_CE64,
    /// ISO 269 "E4" page size (220.0mm x 312.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_E4,
    /// ISO 269 "EC45" page size (220.0mm x 229.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_EC45,
    /// ISO 269 "EC5" page size (155.0mm x 229.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_EC5,
    /// ISO 269 "E5" page size (115.0mm x 220.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_E5,
    /// ISO 269 "E56" page size (155.0mm x 155.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_E56,
    /// ISO 269 "E6" page size (110.0mm x 155.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_E6,
    /// ISO 269 "E65" page size (110.0mm x 220.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_E65,
    /// ISO 269 "R7" page size (120.0mm x 135.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_R7,
    /// ISO 269 "S4" page size (250.0mm x 330.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_S4,
    /// ISO 269 "S5" page size (185.0mm x 255.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_S5,
    /// ISO 269 "S65" page size (110.0mm x 225.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_S65,
    /// ISO 269 "X5" page size (105.0mm x 216.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_X5,
    /// ISO 269 "EX5" page size (155.0mm x 216.0mm)
    HPDF_PAGE_SIZE_ENVELOPE_EX5,

    /// Photography "Passport" page size (35.0mm x 45.0mm)
    HPDF_PAGE_SIZE_PHOTO_PASSPORT,
    /// Photography "2R" page size (64.0mm x 89.0mm)
    HPDF_PAGE_SIZE_PHOTO_2R,
    /// Photography "LD" page size (89.0mm x 119.0mm)
    HPDF_PAGE_SIZE_PHOTO_LD,
    /// Photography "DSC" page size (89.0mm x 119.0mm)
    HPDF_PAGE_SIZE_PHOTO_DSC,
    /// Photography "3R" page size (89.0mm x 127.0mm)
    HPDF_PAGE_SIZE_PHOTO_3R,
    /// Photography "L" page size (89.0mm x 127.0mm)
    HPDF_PAGE_SIZE_PHOTO_L,
    /// Photography "LW" page size (89.0mm x 133.0mm)
    HPDF_PAGE_SIZE_PHOTO_LW,
    /// Photography "KGD" page size (102.0mm x 136.0mm)
    HPDF_PAGE_SIZE_PHOTO_KGD,
    /// Photography "KG" page size (102.0mm x 152.0mm)
    HPDF_PAGE_SIZE_PHOTO_KG,
    /// Photography "4R" page size (102.0mm x 152.0mm)
    HPDF_PAGE_SIZE_PHOTO_4R,
    /// Photography "2LD" page size (127.0mm x 169.0mm)
    HPDF_PAGE_SIZE_PHOTO_2LD,
    /// Photography "DSCW" page size (127.0mm x 169.0mm)
    HPDF_PAGE_SIZE_PHOTO_DSCW,
    /// Photography "2L" page size (127.0mm x 178.0mm)
    HPDF_PAGE_SIZE_PHOTO_2L,
    /// Photography "5R" page size (127.0mm x 178.0mm)
    HPDF_PAGE_SIZE_PHOTO_5R,
    /// Photography "2LW" page size (127.0mm x 190.0mm)
    HPDF_PAGE_SIZE_PHOTO_2LW,
    /// Photography "6R" page size (152.0mm x 203.0mm)
    HPDF_PAGE_SIZE_PHOTO_6R,
    /// Photography "8R" page size (203.0mm x 254.0mm)
    HPDF_PAGE_SIZE_PHOTO_8R,
    /// Photography "6P" page size (203.0mm x 254.0mm)
    HPDF_PAGE_SIZE_PHOTO_6P,
    /// Photography "6PW" page size (203.0mm x 305.0mm)
    HPDF_PAGE_SIZE_PHOTO_6PW,
    /// Photography "S8R" page size (203.0mm x 305.0mm)
    HPDF_PAGE_SIZE_PHOTO_S8R,
    /// Photography "11R" page size (279.0mm x 356.0mm)
    HPDF_PAGE_SIZE_PHOTO_11R,
    /// Photography "A3+ Super B" page size (330.0mm x 483.0mm)
    HPDF_PAGE_SIZE_PHOTO_A3_PLUS,

    /// Newspaper "Berliner" page size (315.0mm x 470.0mm)
    HPDF_PAGE_SIZE_NEWSPAPER_BERLINER,
    /// Newspaper "Broadsheet" page size (597.0mm x 749.0mm)
    HPDF_PAGE_SIZE_NEWSPAPER_BROADSHEET,
    /// Newspaper "US Broadsheet" page size (381.0mm x 578.0mm)
    HPDF_PAGE_SIZE_NEWSPAPER_US_BROADSHEET,
    /// Newspaper "British Broadsheet" page size (375.0mm x 597.0mm)
    HPDF_PAGE_SIZE_NEWSPAPER_BRITISH_BROADSHEET,
    /// Newspaper "South African Broadsheet" page size (410.0mm x 578.0mm)
    HPDF_PAGE_SIZE_NEWSPAPER_SOUTH_AFRICAN_BROADSHEET,
    /// Newspaper "Ciner" page size (350.0mm x 500.0mm)
    HPDF_PAGE_SIZE_NEWSPAPER_CINER,
    /// Newspaper "Compact" page size (280.0mm x 430.0mm)
    HPDF_PAGE_SIZE_NEWSPAPER_COMPACT,
    /// Newspaper "Nordisch" page size (400.0mm x 570.0mm)
    HPDF_PAGE_SIZE_NEWSPAPER_NORDISCH,
    /// Newspaper "Rhenish" page size (350.0mm x 520.0mm)
    HPDF_PAGE_SIZE_NEWSPAPER_RHENISH,
    /// Newspaper "Swiss" page size (320.0mm x 475.0mm)
    HPDF_PAGE_SIZE_NEWSPAPER_SWISS,
    /// Newspaper "Tabloid" page size (280.0mm x 430.0mm)
    HPDF_PAGE_SIZE_NEWSPAPER_TABLOID,
    /// Newspaper "Canadian Tabloid" page size (260.0mm x 368.0mm)
    HPDF_PAGE_SIZE_NEWSPAPER_CANADIAN_TABLOID,
    /// Newspaper "Norwegian Tabloid" page size (280.0mm x 400.0mm)
    HPDF_PAGE_SIZE_NEWSPAPER_NORWEGIAN_TABLOID,
    /// Newspaper "New York Times" page size (305.0mm x 559.0mm)
    HPDF_PAGE_SIZE_NEWSPAPER_NEW_YOUR_TIMES,
    /// Newspaper "Wall Street Journal" page size (305.0mm x 578.0mm)
    HPDF_PAGE_SIZE_NEWSPAPER_WALL_STREET_JOURNAL,

    /// Book "Folio" page size (304.8mm x 482.6mm)
    HPDF_PAGE_SIZE_BOOK_FOLIO,
    /// Book "Quarto" page size (241.3mm x 304.8mm)
    HPDF_PAGE_SIZE_BOOK_QUARTO,
    /// Book "Imperial Octavo" page size (209.6mm x 292.1mm)
    HPDF_PAGE_SIZE_BOOK_IMPERIAL_OCTAVO,
    /// Book "Super Octavo" page size (177.8mm x 279.4mm)
    HPDF_PAGE_SIZE_BOOK_SUPER_OCTAVO,
    /// Book "Royal Octavo" page size (165.1mm x 254.0mm)
    HPDF_PAGE_SIZE_BOOK_ROYAL_OCTAVO,
    /// Book "Medium Octavo" page size (165.1mm x 234.9mm)
    HPDF_PAGE_SIZE_BOOK_MEDIUM_OCTAVO,
    /// Book "Octavo" page size (152.4mm x 228.6mm)
    HPDF_PAGE_SIZE_BOOK_OCTAVO,
    /// Book "Crown Octavo" page size (136.5mm x 203.2mm)
    HPDF_PAGE_SIZE_BOOK_CROWN_OCTAVO,
    /// Book "12mo" page size (127.0mm x 187.3mm)
    HPDF_PAGE_SIZE_BOOK_12MO,
    /// Book "16mo" page size (101.6mm x 171.4mm)
    HPDF_PAGE_SIZE_BOOK_16MO,
    /// Book "18mo" page size (101.6mm x 165.1mm)
    HPDF_PAGE_SIZE_BOOK_18MO,
    /// Book "32mo" page size (88.9mm x 139.7mm)
    HPDF_PAGE_SIZE_BOOK_32MO,
    /// Book "48mo" page size (63.5mm x 101.6mm)
    HPDF_PAGE_SIZE_BOOK_48MO,
    /// Book "64mo" page size (50.8mm x 76.2mm)
    HPDF_PAGE_SIZE_BOOK_64MO,
    /// Book "A Format" page size (110.0mm x 178.0mm)
    HPDF_PAGE_SIZE_BOOK_A_FORMAT,
    /// Book "B Format" page size (129.0mm x 198.0mm)
    HPDF_PAGE_SIZE_BOOK_B_FORMAT,
    /// Book "C Format" page size (135.0mm x 216.0mm)
    HPDF_PAGE_SIZE_BOOK_C_FORMAT,

    /// Business Card "ISO 216" page size (74.0mm x 52.0mm)
    HPDF_PAGE_SIZE_BUSINESS_CARD_ISO_216,
    /// Business Card "US/Canada" page size (88.9mm x 50.8mm)
    HPDF_PAGE_SIZE_BUSINESS_CARD_US_CANADA,
    /// Business Card "European" page size (85.0mm x 55.0mm)
    HPDF_PAGE_SIZE_BUSINESS_CARD_EUROPEAN,
    /// Business Card "Scandinavia" page size (90.0mm x 55.0mm)
    HPDF_PAGE_SIZE_BUSINESS_CARD_SCANDINAVIA,
    /// Business Card "China" page size (90.0mm x 54.0mm)
    HPDF_PAGE_SIZE_BUSINESS_CARD_CHINA,
    /// Business Card "Japan" page size (91.0mm x 55.0mm)
    HPDF_PAGE_SIZE_BUSINESS_CARD_JAPAN,
    /// Business Card "Iran" page size (85.0mm x 48.0mm)
    HPDF_PAGE_SIZE_BUSINESS_CARD_IRAN,
    /// Business Card "Hungary" page size (90.0mm x 50.0mm)
    HPDF_PAGE_SIZE_BUSINESS_CARD_HUNGARY,
    /// Business Card "ISO 7810 ID-1" page size (85.6mm x 54.0mm)
    HPDF_PAGE_SIZE_BUSINESS_CARD_ISO_7810_ID_1,

    /// ISO 217:1995 "RA0" page size (860.0mm x 1220.0mm)
    HPDF_PAGE_SIZE_RAW_RA0,
    /// ISO 217:1995 "RA1" page size (610.0mm x 860.0mm)
    HPDF_PAGE_SIZE_RAW_RA1,
    /// ISO 217:1995 "RA2" page size (430.0mm x 610.0mm)
    HPDF_PAGE_SIZE_RAW_RA2,
    /// ISO 217:1995 "RA3" page size (305.0mm x 430.0mm)
    HPDF_PAGE_SIZE_RAW_RA3,
    /// ISO 217:1995 "RA4" page size (215.0mm x 305.0mm)
    HPDF_PAGE_SIZE_RAW_RA4,
    /// ISO 217:1995 "SRA0" page size (900.0mm x 1280.0mm)
    HPDF_PAGE_SIZE_RAW_SRA0,
    /// ISO 217:1995 "SRA1" page size (640.0mm x 900.0mm)
    HPDF_PAGE_SIZE_RAW_SRA1,
    /// ISO 217:1995 "SRA2" page size (450.0mm x 640.0mm)
    HPDF_PAGE_SIZE_RAW_SRA2,
    /// ISO 217:1995 "SRA3" page size (320.0mm x 450.0mm)
    HPDF_PAGE_SIZE_RAW_SRA3,
    /// ISO 217:1995 "SRA4" page size (225.0mm x 320.0mm)
    HPDF_PAGE_SIZE_RAW_SRA4,
    /// ISO 217:1995 "SRA1+" page size (660.0mm x 920.0mm)
    HPDF_PAGE_SIZE_RAW_SRA1_PLUS,
    /// ISO 217:1995 "SRA2+" page size (480.0mm x 650.0mm)
    HPDF_PAGE_SIZE_RAW_SRA2_PLUS,
    /// ISO 217:1995 "SRA3+" page size (320.0mm x 460.0mm)
    HPDF_PAGE_SIZE_RAW_SRA3_PLUS,
    /// ISO 217:1995 "SRA3++" page size (320.0mm x 464.0mm)
    HPDF_PAGE_SIZE_RAW_SRA3_PLUS_PLUS,
    /// ISO 217:1995 "A0U" page size (880.0mm x 1230.0mm)
    HPDF_PAGE_SIZE_RAW_A0U,
    /// ISO 217:1995 "A1U" page size (625.0mm x 880.0mm)
    HPDF_PAGE_SIZE_RAW_A1U,
    /// ISO 217:1995 "A2U" page size (450.0mm x 625.0mm)
    HPDF_PAGE_SIZE_RAW_A2U,
    /// ISO 217:1995 "A3U" page size (330.0mm x 450.0mm)
    HPDF_PAGE_SIZE_RAW_A3U,
    /// ISO 217:1995 "A4U" page size (240.0mm x 330.0mm)
    HPDF_PAGE_SIZE_RAW_A4U,

    /// Billboard "1 Sheet" page size (508.0mm x 762.0mm)
    HPDF_PAGE_SIZE_BILLBOARD_1_SHEET,
    /// Billboard "2 Sheet" page size (762.0mm x 1016.0mm)
    HPDF_PAGE_SIZE_BILLBOARD_2_SHEET,
    /// Billboard "4 Sheet" page size (1016.0mm x 1524.0mm)
    HPDF_PAGE_SIZE_BILLBOARD_4_SHEET,
    /// Billboard "6 Sheet" page size (1200.0mm x 1800.0mm)
    HPDF_PAGE_SIZE_BILLBOARD_6_SHEET,
    /// Billboard "12 Sheet" page size (3048.0mm x 1524.0mm)
    HPDF_PAGE_SIZE_BILLBOARD_12_SHEET,
    /// Billboard "16 Sheet" page size (2032.0mm x 3048.0mm)
    HPDF_PAGE_SIZE_BILLBOARD_16_SHEET,
    /// Billboard "32 Sheet" page size (4064.0mm x 3048.0mm)
    HPDF_PAGE_SIZE_BILLBOARD_32_SHEET,
    /// Japanese JIS "JB0" page size (1030.0mm x 1456.0mm)
    HPDF_PAGE_SIZE_JAPANESE_JB0,
    /// Japanese JIS "JB1" page size (728.0mm x 1030.0mm)
    HPDF_PAGE_SIZE_JAPANESE_JB1,
    /// Japanese JIS "JB2" page size (515.0mm x 728.0mm)
    HPDF_PAGE_SIZE_JAPANESE_JB2,
    /// Japanese JIS "JB3" page size (364.0mm x 515.0mm)
    HPDF_PAGE_SIZE_JAPANESE_JB3,
    /// Japanese JIS "JB4" page size (257.0mm x 364.0mm)
    HPDF_PAGE_SIZE_JAPANESE_JB4,
    /// Japanese JIS "JB5" page size (182.0mm x 257.0mm)
    HPDF_PAGE_SIZE_JAPANESE_JB5,
    /// Japanese JIS "JB6" page size (128.0mm x 182.0mm)
    HPDF_PAGE_SIZE_JAPANESE_JB6,
    /// Japanese JIS "JB7" page size (91.0mm x 128.0mm)
    HPDF_PAGE_SIZE_JAPANESE_JB7,
    /// Japanese JIS "JB8" page size (64.0mm x 91.0mm)
    HPDF_PAGE_SIZE_JAPANESE_JB8,
    /// Japanese JIS "JB9" page size (45.0mm x 64.0mm)
    HPDF_PAGE_SIZE_JAPANESE_JB9,
    /// Japanese JIS "JB10" page size (32.0mm x 45.0mm)
    HPDF_PAGE_SIZE_JAPANESE_JB10,
    /// Japanese JIS "JB11" page size (22.0mm x 32.0mm)
    HPDF_PAGE_SIZE_JAPANESE_JB11,
    /// Japanese JIS "JB12" page size (16.0mm x 22.0mm)
    HPDF_PAGE_SIZE_JAPANESE_JB12,

    /// Japanese Shiroku "Shiroku ban 4" page size (264.0mm x 379.0mm)
    HPDF_PAGE_SIZE_JAPANESE_SHIROKU_BAN_4,
    /// Japanese Shiroku "Shiroku ban 5" page size (189.0mm x 262.0mm)
    HPDF_PAGE_SIZE_JAPANESE_SHIROKU_BAN_5,
    /// Japanese Shiroku "Shiroku ban 6" page size (127.0mm x 188.0mm)
    HPDF_PAGE_SIZE_JAPANESE_SHIROKU_BAN_6,

    /// Japanese Kiku "Kiku 4" page size (227.0mm x 306.0mm)
    HPDF_PAGE_SIZE_JAPANESE_KIKU_4,
    /// Japanese Kiku "Kiku 5" page size (151.0mm x 227.0mm)
    HPDF_PAGE_SIZE_JAPANESE_KIKU_5,

    /// Canadian CAN 2-9.60M "P1" page size (560.0mm x 860.0mm)
    HPDF_PAGE_SIZE_CANADIAN_P1,
    /// Canadian CAN 2-9.60M "P2" page size (430.0mm x 560.0mm)
    HPDF_PAGE_SIZE_CANADIAN_P2,
    /// Canadian CAN 2-9.60M "P3" page size (280.0mm x 430.0mm)
    HPDF_PAGE_SIZE_CANADIAN_P3,
    /// Canadian CAN 2-9.60M "P4" page size (215.0mm x 280.0mm)
    HPDF_PAGE_SIZE_CANADIAN_P4,
    /// Canadian CAN 2-9.60M "P5" page size (140.0mm x 215.0mm)
    HPDF_PAGE_SIZE_CANADIAN_P5,
    /// Canadian CAN 2-9.60M "P6" page size (107.0mm x 140.0mm)
    HPDF_PAGE_SIZE_CANADIAN_P6,

    /// German DIN 476 "DIN D0" page size (771.0mm x 1090.0mm)
    HPDF_PAGE_SIZE_DIN_D0,
    /// German DIN 476 "DIN D1" page size (545.0mm x 771.0mm)
    HPDF_PAGE_SIZE_DIN_D1,
    /// German DIN 476 "DIN D2" page size (385.0mm x 545.0mm)
    HPDF_PAGE_SIZE_DIN_D2,
    /// German DIN 476 "DIN D3" page size (272.0mm x 385.0mm)
    HPDF_PAGE_SIZE_DIN_D3,
    /// German DIN 476 "DIN D4" page size (192.0mm x 272.0mm)
    HPDF_PAGE_SIZE_DIN_D4,
    /// German DIN 476 "DIN D5" page size (136.0mm x 192.0mm)
    HPDF_PAGE_SIZE_DIN_D5,
    /// German DIN 476 "DIN D6" page size (96.0mm x 136.0mm)
    HPDF_PAGE_SIZE_DIN_D6,
    /// German DIN 476 "DIN D7" page size (68.0mm x 96.0mm)
    HPDF_PAGE_SIZE_DIN_D7,
    /// German DIN 476 "DIN D8" page size (48.0mm x 68.0mm)
    HPDF_PAGE_SIZE_DIN_D8,

    /// Swedish SIS 01 47 11 "SIS E0" page size (878.0mm x 1242.0mm)
    HPDF_PAGE_SIZE_SIS_E0,
    /// Swedish SIS 01 47 11 "SIS E1" page size (621.0mm x 878.0mm)
    HPDF_PAGE_SIZE_SIS_E1,
    /// Swedish SIS 01 47 11 "SIS E2" page size (439.0mm x 621.0mm)
    HPDF_PAGE_SIZE_SIS_E2,
    /// Swedish SIS 01 47 11 "SIS E3" page size (310.0mm x 439.0mm)
    HPDF_PAGE_SIZE_SIS_E3,
    /// Swedish SIS 01 47 11 "SIS E4" page size (220.0mm x 310.0mm)
    HPDF_PAGE_SIZE_SIS_E4,
    /// Swedish SIS 01 47 11 "SIS E5" page size (155.0mm x 220.0mm)
    HPDF_PAGE_SIZE_SIS_E5,
    /// Swedish SIS 01 47 11 "SIS E6" page size (110.0mm x 155.0mm)
    HPDF_PAGE_SIZE_SIS_E6,
    /// Swedish SIS 01 47 11 "SIS E7" page size (78.0mm x 110.0mm)
    HPDF_PAGE_SIZE_SIS_E7,
    /// Swedish SIS 01 47 11 "SIS E8" page size (55.0mm x 78.0mm)
    HPDF_PAGE_SIZE_SIS_E8,
    /// Swedish SIS 01 47 11 "SIS E9" page size (39.0mm x 55.0mm)
    HPDF_PAGE_SIZE_SIS_E9,
    /// Swedish SIS 01 47 11 "SIS E10" page size (27.0mm x 39.0mm)
    HPDF_PAGE_SIZE_SIS_E10,
    /// Swedish SIS 01 47 11 "SIS F0" page size (958.0mm x 1354.0mm)
    HPDF_PAGE_SIZE_SIS_F0,
    /// Swedish SIS 01 47 11 "SIS F1" page size (677.0mm x 958.0mm)
    HPDF_PAGE_SIZE_SIS_F1,
    /// Swedish SIS 01 47 11 "SIS F2" page size (479.0mm x 677.0mm)
    HPDF_PAGE_SIZE_SIS_F2,
    /// Swedish SIS 01 47 11 "SIS F3" page size (339.0mm x 479.0mm)
    HPDF_PAGE_SIZE_SIS_F3,
    /// Swedish SIS 01 47 11 "SIS F4" page size (239.0mm x 339.0mm)
    HPDF_PAGE_SIZE_SIS_F4,
    /// Swedish SIS 01 47 11 "SIS F5" page size (169.0mm x 239.0mm)
    HPDF_PAGE_SIZE_SIS_F5,
    /// Swedish SIS 01 47 11 "SIS F6" page size (120.0mm x 169.0mm)
    HPDF_PAGE_SIZE_SIS_F6,
    /// Swedish SIS 01 47 11 "SIS F7" page size (85.0mm x 120.0mm)
    HPDF_PAGE_SIZE_SIS_F7,
    /// Swedish SIS 01 47 11 "SIS F8" page size (60.0mm x 85.0mm)
    HPDF_PAGE_SIZE_SIS_F8,
    /// Swedish SIS 01 47 11 "SIS F9" page size (42.0mm x 60.0mm)
    HPDF_PAGE_SIZE_SIS_F9,
    /// Swedish SIS 01 47 11 "SIS F10" page size (30.0mm x 42.0mm)
    HPDF_PAGE_SIZE_SIS_F10,
    /// Swedish SIS 01 47 11 "SIS G0" page size (1044.0mm x 1477.0mm)
    HPDF_PAGE_SIZE_SIS_G0,
    /// Swedish SIS 01 47 11 "SIS G1" page size (738.0mm x 1044.0mm)
    HPDF_PAGE_SIZE_SIS_G1,
    /// Swedish SIS 01 47 11 "SIS G2" page size (522.0mm x 738.0mm)
    HPDF_PAGE_SIZE_SIS_G2,
    /// Swedish SIS 01 47 11 "SIS G3" page size (369.0mm x 522.0mm)
    HPDF_PAGE_SIZE_SIS_G3,
    /// Swedish SIS 01 47 11 "SIS G4" page size (261.0mm x 369.0mm)
    HPDF_PAGE_SIZE_SIS_G4,
    /// Swedish SIS 01 47 11 "SIS G5" page size (185.0mm x 261.0mm)
    HPDF_PAGE_SIZE_SIS_G5,
    /// Swedish SIS 01 47 11 "SIS G6" page size (131.0mm x 185.0mm)
    HPDF_PAGE_SIZE_SIS_G6,
    /// Swedish SIS 01 47 11 "SIS G7" page size (92.0mm x 131.0mm)
    HPDF_PAGE_SIZE_SIS_G7,
    /// Swedish SIS 01 47 11 "SIS G8" page size (65.0mm x 92.0mm)
    HPDF_PAGE_SIZE_SIS_G8,
    /// Swedish SIS 01 47 11 "SIS G9" page size (46.0mm x 65.0mm)
    HPDF_PAGE_SIZE_SIS_G9,
    /// Swedish SIS 01 47 11 "SIS G10" page size (33.0mm x 46.0mm)
    HPDF_PAGE_SIZE_SIS_G10,
    /// Swedish SIS 01 47 11 "SIS D0" page size (1091.0mm x 1542.0mm)
    HPDF_PAGE_SIZE_SIS_D0,
    /// Swedish SIS 01 47 11 "SIS D1" page size (771.0mm x 1091.0mm)
    HPDF_PAGE_SIZE_SIS_D1,
    /// Swedish SIS 01 47 11 "SIS D2" page size (545.0mm x 771.0mm)
    HPDF_PAGE_SIZE_SIS_D2,
    /// Swedish SIS 01 47 11 "SIS D3" page size (386.0mm x 545.0mm)
    HPDF_PAGE_SIZE_SIS_D3,
    /// Swedish SIS 01 47 11 "SIS D4" page size (273.0mm x 386.0mm)
    HPDF_PAGE_SIZE_SIS_D4,
    /// Swedish SIS 01 47 11 "SIS D5" page size (193.0mm x 273.0mm)
    HPDF_PAGE_SIZE_SIS_D5,
    /// Swedish SIS 01 47 11 "SIS D6" page size (136.0mm x 193.0mm)
    HPDF_PAGE_SIZE_SIS_D6,
    /// Swedish SIS 01 47 11 "SIS D7" page size (96.0mm x 136.0mm)
    HPDF_PAGE_SIZE_SIS_D7,
    /// Swedish SIS 01 47 11 "SIS D8" page size (68.0mm x 96.0mm)
    HPDF_PAGE_SIZE_SIS_D8,
    /// Swedish SIS 01 47 11 "SIS D9" page size (48.0mm x 68.0mm)
    HPDF_PAGE_SIZE_SIS_D9,
    /// Swedish SIS 01 47 11 "SIS D10" page size (34.0mm x 48.0mm)
    HPDF_PAGE_SIZE_SIS_D10,

    /// Colombian "Carta" page size (216.0mm x 279.0mm)
    HPDF_PAGE_SIZE_COLOMBIAN_CARTA,
    /// Colombian "Extra Tabloide" page size (304.0mm x 457.2mm)
    HPDF_PAGE_SIZE_COLOMBIAN_EXTRA_TABLOIDE,
    /// Colombian "Oficio" page size (216.0mm x 330.0mm)
    HPDF_PAGE_SIZE_COLOMBIAN_OFICIO,
    /// Colombian "1/8 pliego" page size (250.0mm x 350.0mm)
    HPDF_PAGE_SIZE_COLOMBIAN_1_8_PLIEGO,
    /// Colombian "1/4 pliego" page size (350.0mm x 500.0mm)
    HPDF_PAGE_SIZE_COLOMBIAN_1_4_PLIEGO,
    /// Colombian "1/2 pliego" page size (500.0mm x 700.0mm)
    HPDF_PAGE_SIZE_COLOMBIAN_1_2_PLIEGO,
    /// Colombian "Pliego" page size (700.0mm x 1000.0mm)
    HPDF_PAGE_SIZE_COLOMBIAN_PLIEGO,

    /// Chinese GB/T 148-1997 "D0" page size (764.0mm x 1064.0mm)
    HPDF_PAGE_SIZE_CHINESE_D0,
    /// Chinese GB/T 148-1997 "D1" page size (532.0mm x 760.0mm)
    HPDF_PAGE_SIZE_CHINESE_D1,
    /// Chinese GB/T 148-1997 "D2" page size (380.0mm x 528.0mm)
    HPDF_PAGE_SIZE_CHINESE_D2,
    /// Chinese GB/T 148-1997 "D3" page size (264.0mm x 376.0mm)
    HPDF_PAGE_SIZE_CHINESE_D3,
    /// Chinese GB/T 148-1997 "D4" page size (188.0mm x 260.0mm)
    HPDF_PAGE_SIZE_CHINESE_D4,
    /// Chinese GB/T 148-1997 "D5" page size (130.0mm x 184.0mm)
    HPDF_PAGE_SIZE_CHINESE_D5,
    /// Chinese GB/T 148-1997 "D6" page size (92.0mm x 126.0mm)
    HPDF_PAGE_SIZE_CHINESE_D6,
    /// Chinese GB/T 148-1997 "RD0" page size (787.0mm x 1092.0mm)
    HPDF_PAGE_SIZE_CHINESE_RD0,
    /// Chinese GB/T 148-1997 "RD1" page size (546.0mm x 787.0mm)
    HPDF_PAGE_SIZE_CHINESE_RD1,
    /// Chinese GB/T 148-1997 "RD2" page size (393.0mm x 546.0mm)
    HPDF_PAGE_SIZE_CHINESE_RD2,
    /// Chinese GB/T 148-1997 "RD3" page size (273.0mm x 393.0mm)
    HPDF_PAGE_SIZE_CHINESE_RD3,
    /// Chinese GB/T 148-1997 "RD4" page size (196.0mm x 273.0mm)
    HPDF_PAGE_SIZE_CHINESE_RD4,
    /// Chinese GB/T 148-1997 "RD5" page size (136.0mm x 196.0mm)
    HPDF_PAGE_SIZE_CHINESE_RD5,
    /// Chinese GB/T 148-1997 "RD6" page size (98.0mm x 136.0mm)
    HPDF_PAGE_SIZE_CHINESE_RD6,

    /// Transitional PA Series "PA0" page size (840.0mm x 1120.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_PA0,
    /// Transitional PA Series "PA1" page size (560.0mm x 840.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_PA1,
    /// Transitional PA Series "PA2" page size (420.0mm x 560.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_PA2,
    /// Transitional PA Series "PA3" page size (280.0mm x 420.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_PA3,
    /// Transitional PA Series "PA4" page size (210.0mm x 280.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_PA4,
    /// Transitional PA Series "PA5" page size (140.0mm x 210.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_PA5,
    /// Transitional PA Series "PA6" page size (105.0mm x 140.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_PA6,
    /// Transitional PA Series "PA7" page size (70.0mm x 105.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_PA7,
    /// Transitional PA Series "PA8" page size (52.0mm x 70.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_PA8,
    /// Transitional PA Series "PA9" page size (35.0mm x 52.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_PA9,
    /// Transitional PA Series "PA10" page size (26.0mm x 35.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_PA10,

    /// Transitional F Series "F0" page size (841.0mm x 1321.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_F0,
    /// Transitional F Series "F1" page size (660.0mm x 841.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_F1,
    /// Transitional F Series "F2" page size (420.0mm x 660.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_F2,
    /// Transitional F Series "F3" page size (330.0mm x 420.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_F3,
    /// Transitional F Series "F4" page size (210.0mm x 330.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_F4,
    /// Transitional F Series "F5" page size (165.0mm x 210.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_F5,
    /// Transitional F Series "F6" page size (105.0mm x 165.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_F6,
    /// Transitional F Series "F7" page size (82.0mm x 105.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_F7,
    /// Transitional F Series "F8" page size (52.0mm x 82.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_F8,
    /// Transitional F Series "F9" page size (41.0mm x 52.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_F9,
    /// Transitional F Series "F10" page size (26.0mm x 41.0mm)
    HPDF_PAGE_SIZE_TRANSITIONAL_F10,

    /// Imperial "Antiquarian" page size (787.0mm x 1346.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_ANTIQUARIAN,
    /// Imperial "Atlas" page size (660.0mm x 864.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_ATLAS,
    /// Imperial "Brief" page size (343.0mm x 406.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_BRIEF,
    /// Imperial "Broadsheet" page size (457.0mm x 610.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_BROADSHEET,
    /// Imperial "Cartridge" page size (533.0mm x 660.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_CARTRIDGE,
    /// Imperial "Columbier" page size (597.0mm x 876.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_COLUMBIER,
    /// Imperial "Copy Draught" page size (406.0mm x 508.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_COPY_DRAUGHT,
    /// Imperial "Crown" page size (381.0mm x 508.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_CROWN,
    /// Imperial "Demy" page size (445.0mm x 572.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_DEMY,
    /// Imperial "Double Demy" page size (572.0mm x 902.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_DOUBLE_DEMY,
    /// Imperial "Quad Demy" page size (889.0mm x 1143.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_QUAD_DEMY,
    /// Imperial "Elephant" page size (584.0mm x 711.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_ELEPHANT,
    /// Imperial "Double Elephant" page size (678.0mm x 1016.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_DOUBLE_ELEPHANT,
    /// Imperial "Emperor" page size (1219.0mm x 1829.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_EMPEROR,
    /// Imperial "Foolscap" page size (343.0mm x 432.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_FOOLSCAP,
    /// Imperial "Small Foolscap" page size (337.0mm x 419.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_SMALL_FOOLSCAP,
    /// Imperial "Grand Eagle" page size (730.0mm x 1067.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_GRAND_EAGLE,
    /// Imperial "Imperial" page size (559.0mm x 762.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_IMPERIAL,
    /// Imperial "Medium" page size (470.0mm x 584.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_MEDIUM,
    /// Imperial "Monarch" page size (184.0mm x 267.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_MONARCH,
    /// Imperial "Post" page size (394.0mm x 489.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_POST,
    /// Imperial "Sheet, Half Post" page size (495.0mm x 597.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_HALF_POST,
    /// Imperial "Pinched Post" page size (375.0mm x 470.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_PINCHED_POST,
    /// Imperial "Large Post" page size (394.0mm x 508.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_LARGE_POST,
    /// Imperial "Double Large Post" page size (533.0mm x 838.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_DOUBLE_LARGE_POST,
    /// Imperial "Double Post" page size (483.0mm x 762.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_DOUBLE_POST,
    /// Imperial "Pott" page size (318.0mm x 381.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_POTT,
    /// Imperial "Princess" page size (546.0mm x 711.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_PRINCESS,
    /// Imperial "Quarto" page size (229.0mm x 279.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_QUARTO,
    /// Imperial "Royal" page size (508.0mm x 635.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_ROYAL,
    /// Imperial "Super Royal" page size (483.0mm x 686.0mm)
    HPDF_PAGE_SIZE_IMPERIAL_SUPER_ROYAL,

    /// French "Cloche" page size (300.0mm x 400.0mm)
    HPDF_PAGE_SIZE_FRENCH_CLOCHE,
    /// French "Pot, écolier" page size (310.0mm x 400.0mm)
    HPDF_PAGE_SIZE_FRENCH_POT_ECOLIER,
    /// French "Tellière" page size (340.0mm x 440.0mm)
    HPDF_PAGE_SIZE_FRENCH_TELLIERE,
    /// French "Couronne écriture" page size (360.0mm x 360.0mm)
    HPDF_PAGE_SIZE_FRENCH_COURONNE_ECRITURE,
    /// French "Couronne édition" page size (370.0mm x 470.0mm)
    HPDF_PAGE_SIZE_FRENCH_COURONNE_EDITION,
    /// French "Roberto" page size (390.0mm x 500.0mm)
    HPDF_PAGE_SIZE_FRENCH_ROBERTO,
    /// French "Écu" page size (400.0mm x 520.0mm)
    HPDF_PAGE_SIZE_FRENCH_ECU,
    /// French "Coquille" page size (440.0mm x 560.0mm)
    HPDF_PAGE_SIZE_FRENCH_COQUILLE,
    /// French "Carré" page size (450.0mm x 560.0mm)
    HPDF_PAGE_SIZE_FRENCH_CARRE,
    /// French "Cavalier" page size (460.0mm x 620.0mm)
    HPDF_PAGE_SIZE_FRENCH_CAVALIER,
    /// French "Demi-raisin" page size (325.0mm x 500.0mm)
    HPDF_PAGE_SIZE_FRENCH_DEMI_RAISIN,
    /// French "Raisin" page size (500.0mm x 650.0mm)
    HPDF_PAGE_SIZE_FRENCH_RAISIN,
    /// French "Double Raisin" page size (650.0mm x 1000.0mm)
    HPDF_PAGE_SIZE_FRENCH_DOUBLE_RAISIN,
    /// French "Jésus" page size (560.0mm x 760.0mm)
    HPDF_PAGE_SIZE_FRENCH_JESUS,
    /// French "Soleil" page size (600.0mm x 800.0mm)
    HPDF_PAGE_SIZE_FRENCH_SOLEIL,
    /// French "Colombier affiche" page size (600.0mm x 800.0mm)
    HPDF_PAGE_SIZE_FRENCH_COLOMBIER_AFFICHE,
    /// French "Colombier commercial" page size (630.0mm x 900.0mm)
    HPDF_PAGE_SIZE_FRENCH_COLOMBIER_COMMERCIAL,
    /// French "Petit Aigle" page size (700.0mm x 940.0mm)
    HPDF_PAGE_SIZE_FRENCH_PETIT_AIGLE,
    /// French "Grand Aigle" page size (750.0mm x 1050.0mm)
    HPDF_PAGE_SIZE_FRENCH_GRAND_AIGLE,
    /// French "Grand Monde" page size (900.0mm x 1260.0mm)
    HPDF_PAGE_SIZE_FRENCH_GRAND_MONDE,
    /// French "Univers" page size (1000.0mm x 1130.0mm)
    HPDF_PAGE_SIZE_FRENCH_UNIVERS,

    /// Russian GOST 5773-90 "60x84/8" page size (205.0mm x 290.0mm)
    HPDF_PAGE_SIZE_RUSSIAN_60X84_8,
    /// Russian GOST 5773-90 "60x84/16" page size (145.0mm x 200.0mm)
    HPDF_PAGE_SIZE_RUSSIAN_60X84_16,
    /// Russian GOST 5773-90 "60x84/32" page size (100.0mm x 140.0mm)
    HPDF_PAGE_SIZE_RUSSIAN_60X84_32,
    /// Russian GOST 5773-90 "60x90/8" page size (220.0mm x 290.0mm)
    HPDF_PAGE_SIZE_RUSSIAN_60X90_8,
    /// Russian GOST 5773-90 "60x90/16" page size (145.0mm x 215.0mm)
    HPDF_PAGE_SIZE_RUSSIAN_60X90_16,
    /// Russian GOST 5773-90 "70x100/16" page size (170.0mm x 240.0mm)
    HPDF_PAGE_SIZE_RUSSIAN_70X100_16,
    /// Russian GOST 5773-90 "70x100/32" page size (120.0mm x 165.0mm)
    HPDF_PAGE_SIZE_RUSSIAN_70X100_32,
    /// Russian GOST 5773-90 "70x108/8" page size (265.0mm x 340.0mm)
    HPDF_PAGE_SIZE_RUSSIAN_70X108_8,
    /// Russian GOST 5773-90 "70x108/16" page size (170.0mm x 260.0mm)
    HPDF_PAGE_SIZE_RUSSIAN_70X108_16,
    /// Russian GOST 5773-90 "70x108/32" page size (130.0mm x 165.0mm)
    HPDF_PAGE_SIZE_RUSSIAN_70X108_32,
    /// Russian GOST 5773-90 "70x90/16" page size (170.0mm x 215.0mm)
    HPDF_PAGE_SIZE_RUSSIAN_70X90_16,
    /// Russian GOST 5773-90 "70x90/32" page size (107.0mm x 165.0mm)
    HPDF_PAGE_SIZE_RUSSIAN_70X90_32,
    /// Russian GOST 5773-90 "75x90/32" page size (107.0mm x 177.0mm)
    HPDF_PAGE_SIZE_RUSSIAN_75X90_32,
    /// Russian GOST 5773-90 "84x108/16" page size (205.0mm x 260.0mm)
    HPDF_PAGE_SIZE_RUSSIAN_84X108_8,
    /// Russian GOST 5773-90 "84x108/32" page size (130.0mm x 200.0mm)
    HPDF_PAGE_SIZE_RUSSIAN_84X108_32,

    /// Last page size enum value
    HPDF_PAGE_SIZE_EOF
} HPDF_PageSizes;

/**
  \ingroup page
  \brief Predefined page sizes (in points).
*/
static const HPDF_PageSizeValue HPDF_PREDEFINED_PAGE_SIZES[] = {
    {  612.284,  790.866} /* HPDF_PAGE_SIZE_US_LETTER */,
    {  612.284, 1009.134} /* HPDF_PAGE_SIZE_US_LEGAL */,
    {  790.866, 1224.567} /* HPDF_PAGE_SIZE_US_TABLOID */,
    { 1224.567,  790.866} /* HPDF_PAGE_SIZE_US_LEDGER */,
    {  360.000,  575.433} /* HPDF_PAGE_SIZE_US_JUNIOR_LEGAL */,
    {  396.850,  612.284} /* HPDF_PAGE_SIZE_US_HALF_LETTER */,
    {  575.433,  756.850} /* HPDF_PAGE_SIZE_US_GOVERNMENT_LETTER */,
    {  612.284,  935.433} /* HPDF_PAGE_SIZE_US_GOVERNMENT_LEGAL */,

    {  612.284,  790.866} /* HPDF_PAGE_SIZE_US_ANSI_A */,
    {  790.866, 1224.567} /* HPDF_PAGE_SIZE_US_ANSI_B */,
    { 1224.567, 1584.567} /* HPDF_PAGE_SIZE_US_ANSI_C */,
    { 1584.567, 2449.134} /* HPDF_PAGE_SIZE_US_ANSI_D */,
    { 2449.134, 3169.134} /* HPDF_PAGE_SIZE_US_ANSI_E */,

    {  649.134,  864.567} /* HPDF_PAGE_SIZE_US_ARCH_A */,
    {  864.567, 1295.433} /* HPDF_PAGE_SIZE_US_ARCH_B */,
    { 1295.433, 1729.134} /* HPDF_PAGE_SIZE_US_ARCH_C */,
    { 1729.134, 2590.866} /* HPDF_PAGE_SIZE_US_ARCH_D */,
    { 2590.866, 3455.433} /* HPDF_PAGE_SIZE_US_ARCH_E */,
    { 2160.000, 3024.567} /* HPDF_PAGE_SIZE_US_ARCH_E1 */,
    { 1870.866, 2735.433} /* HPDF_PAGE_SIZE_US_ARCH_E2 */,
    { 1944.567, 2809.134} /* HPDF_PAGE_SIZE_US_ARCH_E3 */,

    { 4767.875, 6740.788} /* HPDF_PAGE_SIZE_4A0 */,
    { 3370.394, 4767.875} /* HPDF_PAGE_SIZE_2A0 */,
    { 2383.937, 3370.394} /* HPDF_PAGE_SIZE_A0 */,
    { 2590.866, 3662.363} /* HPDF_PAGE_SIZE_A0_PLUS */,
    { 1683.780, 2383.937} /* HPDF_PAGE_SIZE_A1 */,
    { 1726.299, 2590.866} /* HPDF_PAGE_SIZE_A1_PLUS */,
    { 1190.551, 1683.780} /* HPDF_PAGE_SIZE_A2 */,
    {  841.890, 1190.551} /* HPDF_PAGE_SIZE_A3 */,
    {  932.599, 1369.134} /* HPDF_PAGE_SIZE_A3_PLUS */,
    {  595.276,  841.890} /* HPDF_PAGE_SIZE_A4 */,
    {  419.528,  595.276} /* HPDF_PAGE_SIZE_A5 */,
    {  297.638,  419.528} /* HPDF_PAGE_SIZE_A6 */,
    {  209.764,  297.638} /* HPDF_PAGE_SIZE_A7 */,
    {  147.402,  209.764} /* HPDF_PAGE_SIZE_A8 */,
    {  104.882,  147.402} /* HPDF_PAGE_SIZE_A9 */,
    {   73.701,  104.882} /* HPDF_PAGE_SIZE_A10 */,
    { 2834.646, 4008.189} /* HPDF_PAGE_SIZE_B0 */,
    { 3169.134, 4478.741} /* HPDF_PAGE_SIZE_B0_PLUS */,
    { 2004.095, 2834.646} /* HPDF_PAGE_SIZE_B1 */,
    { 2040.945, 2891.339} /* HPDF_PAGE_SIZE_B1_PLUS */,
    { 1417.323, 2004.095} /* HPDF_PAGE_SIZE_B2 */,
    { 1474.016, 2040.945} /* HPDF_PAGE_SIZE_B2_PLUS */,
    { 1000.630, 1417.323} /* HPDF_PAGE_SIZE_B3 */,
    {  708.662, 1000.630} /* HPDF_PAGE_SIZE_B4 */,
    {  498.898,  708.662} /* HPDF_PAGE_SIZE_B5 */,
    {  354.331,  498.898} /* HPDF_PAGE_SIZE_B6 */,
    {  249.449,  354.331} /* HPDF_PAGE_SIZE_B7 */,
    {  175.748,  249.449} /* HPDF_PAGE_SIZE_B8 */,
    {  124.724,  175.748} /* HPDF_PAGE_SIZE_B9 */,
    {   87.874,  124.724} /* HPDF_PAGE_SIZE_B10 */,
    {   62.362,   87.874} /* HPDF_PAGE_SIZE_B11 */,
    {   42.520,   62.362} /* HPDF_PAGE_SIZE_B12 */,
    {   31.181,   42.520} /* HPDF_PAGE_SIZE_B13 */,
    { 2599.370, 3676.536} /* HPDF_PAGE_SIZE_C0 */,
    { 1836.851, 2599.370} /* HPDF_PAGE_SIZE_C1 */,
    { 1298.268, 1836.851} /* HPDF_PAGE_SIZE_C2 */,
    {  918.425, 1298.268} /* HPDF_PAGE_SIZE_C3 */,
    {  649.134,  918.425} /* HPDF_PAGE_SIZE_C4 */,
    {  459.213,  649.134} /* HPDF_PAGE_SIZE_C5 */,
    {  323.150,  459.213} /* HPDF_PAGE_SIZE_C6 */,
    {  229.606,  323.150} /* HPDF_PAGE_SIZE_C7 */,
    {  161.575,  229.606} /* HPDF_PAGE_SIZE_C8 */,
    {  113.386,  161.575} /* HPDF_PAGE_SIZE_C9 */,
    {   79.370,  113.386} /* HPDF_PAGE_SIZE_C10 */,

    {  396.850,  504.567} /* HPDF_PAGE_SIZE_BRITISH_DUKES */,
    {  575.433,  935.433} /* HPDF_PAGE_SIZE_BRITISH_FOOLSCAP */,
    {  504.567,  649.134} /* HPDF_PAGE_SIZE_BRITISH_IMPERIAL */,
    {  467.717,  575.433} /* HPDF_PAGE_SIZE_BRITISH_KINGS */,
    {  575.433,  720.000} /* HPDF_PAGE_SIZE_BRITISH_QUARTO */,

    {  430.866,  252.283} /* HPDF_PAGE_SIZE_US_ENVELOPE_6_1_4 */,
    {  467.717,  260.787} /* HPDF_PAGE_SIZE_US_ENVELOPE_6_3_4 */,
    {  487.559,  269.291} /* HPDF_PAGE_SIZE_US_ENVELOPE_7 */,
    {  541.417,  277.795} /* HPDF_PAGE_SIZE_US_ENVELOPE_7_3_4_MONARCH */,
    {  620.787,  260.787} /* HPDF_PAGE_SIZE_US_ENVELOPE8_5_8 */,
    {  637.795,  277.795} /* HPDF_PAGE_SIZE_US_ENVELOPE_9 */,
    {  683.150,  294.803} /* HPDF_PAGE_SIZE_US_ENVELOPE_10 */,
    {  748.347,  323.150} /* HPDF_PAGE_SIZE_US_ENVELOPE_11 */,
    {  790.866,  342.992} /* HPDF_PAGE_SIZE_US_ENVELOPE_12 */,
    {  827.717,  360.000} /* HPDF_PAGE_SIZE_US_ENVELOPE_14 */,
    {  864.567,  430.866} /* HPDF_PAGE_SIZE_US_ENVELOPE_16 */,

    {  260.787,  368.504} /* HPDF_PAGE_SIZE_US_ENVELOPE_A1 */,
    {  413.858,  314.646} /* HPDF_PAGE_SIZE_US_ENVELOPE_A2_LADY_GREY */,
    {  450.709,  306.142} /* HPDF_PAGE_SIZE_US_ENVELOPE_A4 */,
    {  467.717,  342.992} /* HPDF_PAGE_SIZE_US_ENVELOPE_A6_THOMPSON_S_STANDARD */,
    {  521.575,  377.008} /* HPDF_PAGE_SIZE_US_ENVELOPE_A7_BESSELHEIM */,
    {  583.937,  396.850} /* HPDF_PAGE_SIZE_US_ENVELOPE_A8_CARR_S */,
    {  629.291,  413.858} /* HPDF_PAGE_SIZE_US_ENVELOPE_A9_DIPLOMAT */,
    {  683.150,  430.866} /* HPDF_PAGE_SIZE_US_ENVELOPE_A10_WILLOW */,
    {  637.795,  277.795} /* HPDF_PAGE_SIZE_US_ENVELOPE_A_LONG */,

    {  649.134,  430.866} /* HPDF_PAGE_SIZE_US_ENVELOPE_1 */,
    {  683.150,  430.866} /* HPDF_PAGE_SIZE_US_ENVELOPE_1_3_4 */,
    {  720.000,  504.567} /* HPDF_PAGE_SIZE_US_ENVELOPE_3 */,
    {  756.850,  541.417} /* HPDF_PAGE_SIZE_US_ENVELOPE_6 */,
    {  810.709,  595.276} /* HPDF_PAGE_SIZE_US_ENVELOPE_8 */,
    {  810.709,  629.291} /* HPDF_PAGE_SIZE_US_ENVELOPE_9_3_4 */,
    {  864.567,  649.134} /* HPDF_PAGE_SIZE_US_ENVELOPE_10_1_2 */,
    {  901.417,  683.150} /* HPDF_PAGE_SIZE_US_ENVELOPE_12_1_2 */,
    {  935.433,  720.000} /* HPDF_PAGE_SIZE_US_ENVELOPE_13_1_2 */,
    { 1043.150,  827.717} /* HPDF_PAGE_SIZE_US_ENVELOPE_14_1_2 */,
    { 1080.000,  720.000} /* HPDF_PAGE_SIZE_US_ENVELOPE_15 */,
    { 1116.851,  864.567} /* HPDF_PAGE_SIZE_US_ENVELOPE_15_1_2 */,

    {  311.811,  623.622} /* HPDF_PAGE_SIZE_ENVELOPE_DL */,
    {  708.662, 1000.630} /* HPDF_PAGE_SIZE_ENVELOPE_B4 */,
    {  498.898,  708.662} /* HPDF_PAGE_SIZE_ENVELOPE_B5 */,
    {  354.331,  498.898} /* HPDF_PAGE_SIZE_ENVELOPE_B6 */,
    {  918.425, 1298.268} /* HPDF_PAGE_SIZE_ENVELOPE_C3 */,
    {  649.134,  918.425} /* HPDF_PAGE_SIZE_ENVELOPE_C4 */,
    {  901.417,  649.134} /* HPDF_PAGE_SIZE_ENVELOPE_C4M */,
    {  459.213,  649.134} /* HPDF_PAGE_SIZE_ENVELOPE_C5 */,
    {  323.150,  649.134} /* HPDF_PAGE_SIZE_ENVELOPE_C6_C5 */,
    {  323.150,  459.213} /* HPDF_PAGE_SIZE_ENVELOPE_C6 */,
    {  901.417,  323.150} /* HPDF_PAGE_SIZE_ENVELOPE_C64M */,
    {  229.606,  459.213} /* HPDF_PAGE_SIZE_ENVELOPE_C7_C6 */,
    {  229.606,  323.150} /* HPDF_PAGE_SIZE_ENVELOPE_C7 */,
    {  649.134,  878.740} /* HPDF_PAGE_SIZE_ENVELOPE_CE4 */,
    {  323.150,  878.740} /* HPDF_PAGE_SIZE_ENVELOPE_CE64 */,
    {  623.622,  884.410} /* HPDF_PAGE_SIZE_ENVELOPE_E4 */,
    {  623.622,  649.134} /* HPDF_PAGE_SIZE_ENVELOPE_EC45 */,
    {  439.370,  649.134} /* HPDF_PAGE_SIZE_ENVELOPE_EC5 */,
    {  325.984,  623.622} /* HPDF_PAGE_SIZE_ENVELOPE_E5 */,
    {  439.370,  439.370} /* HPDF_PAGE_SIZE_ENVELOPE_E56 */,
    {  311.811,  439.370} /* HPDF_PAGE_SIZE_ENVELOPE_E6 */,
    {  311.811,  623.622} /* HPDF_PAGE_SIZE_ENVELOPE_E65 */,
    {  340.158,  382.677} /* HPDF_PAGE_SIZE_ENVELOPE_R7 */,
    {  708.662,  935.433} /* HPDF_PAGE_SIZE_ENVELOPE_S4 */,
    {  524.410,  722.835} /* HPDF_PAGE_SIZE_ENVELOPE_S5 */,
    {  311.811,  637.795} /* HPDF_PAGE_SIZE_ENVELOPE_S65 */,
    {  297.638,  612.284} /* HPDF_PAGE_SIZE_ENVELOPE_X5 */,
    {  439.370,  612.284} /* HPDF_PAGE_SIZE_ENVELOPE_EX5 */,

    {   99.213,  127.559} /* HPDF_PAGE_SIZE_PHOTO_PASSPORT */,
    {  181.417,  252.283} /* HPDF_PAGE_SIZE_PHOTO_2R */,
    {  252.283,  337.323} /* HPDF_PAGE_SIZE_PHOTO_LD */,
    {  252.283,  337.323} /* HPDF_PAGE_SIZE_PHOTO_DSC */,
    {  252.283,  360.000} /* HPDF_PAGE_SIZE_PHOTO_3R */,
    {  252.283,  360.000} /* HPDF_PAGE_SIZE_PHOTO_L */,
    {  252.283,  377.008} /* HPDF_PAGE_SIZE_PHOTO_LW */,
    {  289.134,  385.512} /* HPDF_PAGE_SIZE_PHOTO_KGD */,
    {  289.134,  430.866} /* HPDF_PAGE_SIZE_PHOTO_KG */,
    {  289.134,  430.866} /* HPDF_PAGE_SIZE_PHOTO_4R */,
    {  360.000,  479.055} /* HPDF_PAGE_SIZE_PHOTO_2LD */,
    {  360.000,  479.055} /* HPDF_PAGE_SIZE_PHOTO_DSCW */,
    {  360.000,  504.567} /* HPDF_PAGE_SIZE_PHOTO_2L */,
    {  360.000,  504.567} /* HPDF_PAGE_SIZE_PHOTO_5R */,
    {  360.000,  538.583} /* HPDF_PAGE_SIZE_PHOTO_2LW */,
    {  430.866,  575.433} /* HPDF_PAGE_SIZE_PHOTO_6R */,
    {  575.433,  720.000} /* HPDF_PAGE_SIZE_PHOTO_8R */,
    {  575.433,  720.000} /* HPDF_PAGE_SIZE_PHOTO_6P */,
    {  575.433,  864.567} /* HPDF_PAGE_SIZE_PHOTO_6PW */,
    {  575.433,  864.567} /* HPDF_PAGE_SIZE_PHOTO_S8R */,
    {  790.866, 1009.134} /* HPDF_PAGE_SIZE_PHOTO_11R */,
    {  935.433, 1369.134} /* HPDF_PAGE_SIZE_PHOTO_A3_PLUS */,

    {  892.913, 1332.284} /* HPDF_PAGE_SIZE_NEWSPAPER_BERLINER */,
    { 1692.284, 2123.150} /* HPDF_PAGE_SIZE_NEWSPAPER_BROADSHEET */,
    { 1080.000, 1638.425} /* HPDF_PAGE_SIZE_NEWSPAPER_US_BROADSHEET */,
    { 1062.992, 1692.284} /* HPDF_PAGE_SIZE_NEWSPAPER_BRITISH_BROADSHEET */,
    { 1162.205, 1638.425} /* HPDF_PAGE_SIZE_NEWSPAPER_SOUTH_AFRICAN_BROADSHEET */,
    {  992.126, 1417.323} /* HPDF_PAGE_SIZE_NEWSPAPER_CINER */,
    {  793.701, 1218.898} /* HPDF_PAGE_SIZE_NEWSPAPER_COMPACT */,
    { 1133.858, 1615.748} /* HPDF_PAGE_SIZE_NEWSPAPER_NORDISCH */,
    {  992.126, 1474.016} /* HPDF_PAGE_SIZE_NEWSPAPER_RHENISH */,
    {  907.087, 1346.457} /* HPDF_PAGE_SIZE_NEWSPAPER_SWISS */,
    {  793.701, 1218.898} /* HPDF_PAGE_SIZE_NEWSPAPER_TABLOID */,
    {  737.008, 1043.150} /* HPDF_PAGE_SIZE_NEWSPAPER_CANADIAN_TABLOID */,
    {  793.701, 1133.858} /* HPDF_PAGE_SIZE_NEWSPAPER_NORWEGIAN_TABLOID */,
    {  864.567, 1584.567} /* HPDF_PAGE_SIZE_NEWSPAPER_NEW_YOUR_TIMES */,
    {  864.567, 1638.425} /* HPDF_PAGE_SIZE_NEWSPAPER_WALL_STREET_JOURNAL */,

    {  864.000, 1368.000} /* HPDF_PAGE_SIZE_BOOK_FOLIO */,
    {  684.000,  864.000} /* HPDF_PAGE_SIZE_BOOK_QUARTO */,
    {  594.142,  828.000} /* HPDF_PAGE_SIZE_BOOK_IMPERIAL_OCTAVO */,
    {  504.000,  792.000} /* HPDF_PAGE_SIZE_BOOK_SUPER_OCTAVO */,
    {  468.000,  720.000} /* HPDF_PAGE_SIZE_BOOK_ROYAL_OCTAVO */,
    {  468.000,  665.858} /* HPDF_PAGE_SIZE_BOOK_MEDIUM_OCTAVO */,
    {  432.000,  648.000} /* HPDF_PAGE_SIZE_BOOK_OCTAVO */,
    {  386.929,  576.000} /* HPDF_PAGE_SIZE_BOOK_CROWN_OCTAVO */,
    {  360.000,  530.929} /* HPDF_PAGE_SIZE_BOOK_12MO */,
    {  288.000,  485.858} /* HPDF_PAGE_SIZE_BOOK_16MO */,
    {  288.000,  468.000} /* HPDF_PAGE_SIZE_BOOK_18MO */,
    {  252.000,  396.000} /* HPDF_PAGE_SIZE_BOOK_32MO */,
    {  180.000,  288.000} /* HPDF_PAGE_SIZE_BOOK_48MO */,
    {  144.000,  216.000} /* HPDF_PAGE_SIZE_BOOK_64MO */,
    {  311.811,  504.567} /* HPDF_PAGE_SIZE_BOOK_A_FORMAT */,
    {  365.669,  561.260} /* HPDF_PAGE_SIZE_BOOK_B_FORMAT */,
    {  382.677,  612.284} /* HPDF_PAGE_SIZE_BOOK_C_FORMAT */,

    {  209.764,  147.402} /* HPDF_PAGE_SIZE_BUSINESS_CARD_ISO_216 */,
    {  252.000,  144.000} /* HPDF_PAGE_SIZE_BUSINESS_CARD_US_CANADA */,
    {  240.945,  155.906} /* HPDF_PAGE_SIZE_BUSINESS_CARD_EUROPEAN */,
    {  255.118,  155.906} /* HPDF_PAGE_SIZE_BUSINESS_CARD_SCANDINAVIA */,
    {  255.118,  153.071} /* HPDF_PAGE_SIZE_BUSINESS_CARD_CHINA */,
    {  257.953,  155.906} /* HPDF_PAGE_SIZE_BUSINESS_CARD_JAPAN */,
    {  240.945,  136.063} /* HPDF_PAGE_SIZE_BUSINESS_CARD_IRAN */,
    {  255.118,  141.732} /* HPDF_PAGE_SIZE_BUSINESS_CARD_HUNGARY */,
    {  242.646,  153.071} /* HPDF_PAGE_SIZE_BUSINESS_CARD_ISO_7810_ID_1 */,

    { 2437.796, 3458.268} /* HPDF_PAGE_SIZE_RAW_RA0 */,
    { 1729.134, 2437.796} /* HPDF_PAGE_SIZE_RAW_RA1 */,
    { 1218.898, 1729.134} /* HPDF_PAGE_SIZE_RAW_RA2 */,
    {  864.567, 1218.898} /* HPDF_PAGE_SIZE_RAW_RA3 */,
    {  609.449,  864.567} /* HPDF_PAGE_SIZE_RAW_RA4 */,
    { 2551.181, 3628.347} /* HPDF_PAGE_SIZE_RAW_SRA0 */,
    { 1814.173, 2551.181} /* HPDF_PAGE_SIZE_RAW_SRA1 */,
    { 1275.591, 1814.173} /* HPDF_PAGE_SIZE_RAW_SRA2 */,
    {  907.087, 1275.591} /* HPDF_PAGE_SIZE_RAW_SRA3 */,
    {  637.795,  907.087} /* HPDF_PAGE_SIZE_RAW_SRA4 */,
    { 1870.866, 2607.874} /* HPDF_PAGE_SIZE_RAW_SRA1_PLUS */,
    { 1360.630, 1842.520} /* HPDF_PAGE_SIZE_RAW_SRA2_PLUS */,
    {  907.087, 1303.937} /* HPDF_PAGE_SIZE_RAW_SRA3_PLUS */,
    {  907.087, 1315.276} /* HPDF_PAGE_SIZE_RAW_SRA3_PLUS_PLUS */,
    { 2494.488, 3486.615} /* HPDF_PAGE_SIZE_RAW_A0U */,
    { 1771.654, 2494.488} /* HPDF_PAGE_SIZE_RAW_A1U */,
    { 1275.591, 1771.654} /* HPDF_PAGE_SIZE_RAW_A2U */,
    {  935.433, 1275.591} /* HPDF_PAGE_SIZE_RAW_A3U */,
    {  680.315,  935.433} /* HPDF_PAGE_SIZE_RAW_A4U */,

    { 1440.000, 2160.000} /* HPDF_PAGE_SIZE_BILLBOARD_1_SHEET */,
    { 2160.000, 2880.000} /* HPDF_PAGE_SIZE_BILLBOARD_2_SHEET */,
    { 2880.000, 4320.001} /* HPDF_PAGE_SIZE_BILLBOARD_4_SHEET */,
    { 3401.575, 5102.363} /* HPDF_PAGE_SIZE_BILLBOARD_6_SHEET */,
    { 8640.001, 4320.001} /* HPDF_PAGE_SIZE_BILLBOARD_12_SHEET */,
    { 5760.001, 8640.001} /* HPDF_PAGE_SIZE_BILLBOARD_16_SHEET */,
    {11520.001, 8640.001} /* HPDF_PAGE_SIZE_BILLBOARD_32_SHEET */,
    { 2919.685, 4127.245} /* HPDF_PAGE_SIZE_JAPANESE_JB0 */,
    { 2063.622, 2919.685} /* HPDF_PAGE_SIZE_JAPANESE_JB1 */,
    { 1459.843, 2063.622} /* HPDF_PAGE_SIZE_JAPANESE_JB2 */,
    { 1031.811, 1459.843} /* HPDF_PAGE_SIZE_JAPANESE_JB3 */,
    {  728.504, 1031.811} /* HPDF_PAGE_SIZE_JAPANESE_JB4 */,
    {  515.906,  728.504} /* HPDF_PAGE_SIZE_JAPANESE_JB5 */,
    {  362.835,  515.906} /* HPDF_PAGE_SIZE_JAPANESE_JB6 */,
    {  257.953,  362.835} /* HPDF_PAGE_SIZE_JAPANESE_JB7 */,
    {  181.417,  257.953} /* HPDF_PAGE_SIZE_JAPANESE_JB8 */,
    {  127.559,  181.417} /* HPDF_PAGE_SIZE_JAPANESE_JB9 */,
    {   90.709,  127.559} /* HPDF_PAGE_SIZE_JAPANESE_JB10 */,
    {   62.362,   90.709} /* HPDF_PAGE_SIZE_JAPANESE_JB11 */,
    {   45.354,   62.362} /* HPDF_PAGE_SIZE_JAPANESE_JB12 */,

    {  748.347, 1074.331} /* HPDF_PAGE_SIZE_JAPANESE_SHIROKU_BAN_4 */,
    {  535.748,  742.677} /* HPDF_PAGE_SIZE_JAPANESE_SHIROKU_BAN_5 */,
    {  360.000,  532.913} /* HPDF_PAGE_SIZE_JAPANESE_SHIROKU_BAN_6 */,

    {  643.465,  867.402} /* HPDF_PAGE_SIZE_JAPANESE_KIKU_4 */,
    {  428.032,  643.465} /* HPDF_PAGE_SIZE_JAPANESE_KIKU_5 */,

    { 1587.402, 2437.796} /* HPDF_PAGE_SIZE_CANADIAN_P1 */,
    { 1218.898, 1587.402} /* HPDF_PAGE_SIZE_CANADIAN_P2 */,
    {  793.701, 1218.898} /* HPDF_PAGE_SIZE_CANADIAN_P3 */,
    {  609.449,  793.701} /* HPDF_PAGE_SIZE_CANADIAN_P4 */,
    {  396.850,  609.449} /* HPDF_PAGE_SIZE_CANADIAN_P5 */,
    {  303.307,  396.850} /* HPDF_PAGE_SIZE_CANADIAN_P6 */,

    { 2185.512, 3089.764} /* HPDF_PAGE_SIZE_DIN_D0 */,
    { 1544.882, 2185.512} /* HPDF_PAGE_SIZE_DIN_D1 */,
    { 1091.339, 1544.882} /* HPDF_PAGE_SIZE_DIN_D2 */,
    {  771.024, 1091.339} /* HPDF_PAGE_SIZE_DIN_D3 */,
    {  544.252,  771.024} /* HPDF_PAGE_SIZE_DIN_D4 */,
    {  385.512,  544.252} /* HPDF_PAGE_SIZE_DIN_D5 */,
    {  272.126,  385.512} /* HPDF_PAGE_SIZE_DIN_D6 */,
    {  192.756,  272.126} /* HPDF_PAGE_SIZE_DIN_D7 */,
    {  136.063,  192.756} /* HPDF_PAGE_SIZE_DIN_D8 */,

    { 2488.819, 3520.630} /* HPDF_PAGE_SIZE_SIS_E0 */,
    { 1760.315, 2488.819} /* HPDF_PAGE_SIZE_SIS_E1 */,
    { 1244.410, 1760.315} /* HPDF_PAGE_SIZE_SIS_E2 */,
    {  878.740, 1244.410} /* HPDF_PAGE_SIZE_SIS_E3 */,
    {  623.622,  878.740} /* HPDF_PAGE_SIZE_SIS_E4 */,
    {  439.370,  623.622} /* HPDF_PAGE_SIZE_SIS_E5 */,
    {  311.811,  439.370} /* HPDF_PAGE_SIZE_SIS_E6 */,
    {  221.102,  311.811} /* HPDF_PAGE_SIZE_SIS_E7 */,
    {  155.906,  221.102} /* HPDF_PAGE_SIZE_SIS_E8 */,
    {  110.551,  155.906} /* HPDF_PAGE_SIZE_SIS_E9 */,
    {   76.535,  110.551} /* HPDF_PAGE_SIZE_SIS_E10 */,
    { 2715.591, 3838.111} /* HPDF_PAGE_SIZE_SIS_F0 */,
    { 1919.055, 2715.591} /* HPDF_PAGE_SIZE_SIS_F1 */,
    { 1357.795, 1919.055} /* HPDF_PAGE_SIZE_SIS_F2 */,
    {  960.945, 1357.795} /* HPDF_PAGE_SIZE_SIS_F3 */,
    {  677.480,  960.945} /* HPDF_PAGE_SIZE_SIS_F4 */,
    {  479.055,  677.480} /* HPDF_PAGE_SIZE_SIS_F5 */,
    {  340.158,  479.055} /* HPDF_PAGE_SIZE_SIS_F6 */,
    {  240.945,  340.158} /* HPDF_PAGE_SIZE_SIS_F7 */,
    {  170.079,  240.945} /* HPDF_PAGE_SIZE_SIS_F8 */,
    {  119.055,  170.079} /* HPDF_PAGE_SIZE_SIS_F9 */,
    {   85.039,  119.055} /* HPDF_PAGE_SIZE_SIS_F10 */,
    { 2959.370, 4186.772} /* HPDF_PAGE_SIZE_SIS_G0 */,
    { 2091.969, 2959.370} /* HPDF_PAGE_SIZE_SIS_G1 */,
    { 1479.685, 2091.969} /* HPDF_PAGE_SIZE_SIS_G2 */,
    { 1045.984, 1479.685} /* HPDF_PAGE_SIZE_SIS_G3 */,
    {  739.843, 1045.984} /* HPDF_PAGE_SIZE_SIS_G4 */,
    {  524.410,  739.843} /* HPDF_PAGE_SIZE_SIS_G5 */,
    {  371.339,  524.410} /* HPDF_PAGE_SIZE_SIS_G6 */,
    {  260.787,  371.339} /* HPDF_PAGE_SIZE_SIS_G7 */,
    {  184.252,  260.787} /* HPDF_PAGE_SIZE_SIS_G8 */,
    {  130.394,  184.252} /* HPDF_PAGE_SIZE_SIS_G9 */,
    {   93.543,  130.394} /* HPDF_PAGE_SIZE_SIS_G10 */,
    { 3092.599, 4371.024} /* HPDF_PAGE_SIZE_SIS_D0 */,
    { 2185.512, 3092.599} /* HPDF_PAGE_SIZE_SIS_D1 */,
    { 1544.882, 2185.512} /* HPDF_PAGE_SIZE_SIS_D2 */,
    { 1094.173, 1544.882} /* HPDF_PAGE_SIZE_SIS_D3 */,
    {  773.858, 1094.173} /* HPDF_PAGE_SIZE_SIS_D4 */,
    {  547.087,  773.858} /* HPDF_PAGE_SIZE_SIS_D5 */,
    {  385.512,  547.087} /* HPDF_PAGE_SIZE_SIS_D6 */,
    {  272.126,  385.512} /* HPDF_PAGE_SIZE_SIS_D7 */,
    {  192.756,  272.126} /* HPDF_PAGE_SIZE_SIS_D8 */,
    {  136.063,  192.756} /* HPDF_PAGE_SIZE_SIS_D9 */,
    {   96.378,  136.063} /* HPDF_PAGE_SIZE_SIS_D10 */,

    {  612.284,  790.866} /* HPDF_PAGE_SIZE_COLOMBIAN_CARTA */,
    {  861.732, 1296.000} /* HPDF_PAGE_SIZE_COLOMBIAN_EXTRA_TABLOIDE */,
    {  612.284,  935.433} /* HPDF_PAGE_SIZE_COLOMBIAN_OFICIO */,
    {  708.662,  992.126} /* HPDF_PAGE_SIZE_COLOMBIAN_1_8_PLIEGO */,
    {  992.126, 1417.323} /* HPDF_PAGE_SIZE_COLOMBIAN_1_4_PLIEGO */,
    { 1417.323, 1984.252} /* HPDF_PAGE_SIZE_COLOMBIAN_1_2_PLIEGO */,
    { 1984.252, 2834.646} /* HPDF_PAGE_SIZE_COLOMBIAN_PLIEGO */,

    { 2165.670, 3016.063} /* HPDF_PAGE_SIZE_CHINESE_D0 */,
    { 1508.032, 2154.331} /* HPDF_PAGE_SIZE_CHINESE_D1 */,
    { 1077.165, 1496.693} /* HPDF_PAGE_SIZE_CHINESE_D2 */,
    {  748.347, 1065.827} /* HPDF_PAGE_SIZE_CHINESE_D3 */,
    {  532.913,  737.008} /* HPDF_PAGE_SIZE_CHINESE_D4 */,
    {  368.504,  521.575} /* HPDF_PAGE_SIZE_CHINESE_D5 */,
    {  260.787,  357.165} /* HPDF_PAGE_SIZE_CHINESE_D6 */,
    { 2230.866, 3095.433} /* HPDF_PAGE_SIZE_CHINESE_RD0 */,
    { 1547.717, 2230.866} /* HPDF_PAGE_SIZE_CHINESE_RD1 */,
    { 1114.016, 1547.717} /* HPDF_PAGE_SIZE_CHINESE_RD2 */,
    {  773.858, 1114.016} /* HPDF_PAGE_SIZE_CHINESE_RD3 */,
    {  555.591,  773.858} /* HPDF_PAGE_SIZE_CHINESE_RD4 */,
    {  385.512,  555.591} /* HPDF_PAGE_SIZE_CHINESE_RD5 */,
    {  277.795,  385.512} /* HPDF_PAGE_SIZE_CHINESE_RD6 */,

    { 2381.103, 3174.804} /* HPDF_PAGE_SIZE_TRANSITIONAL_PA0 */,
    { 1587.402, 2381.103} /* HPDF_PAGE_SIZE_TRANSITIONAL_PA1 */,
    { 1190.551, 1587.402} /* HPDF_PAGE_SIZE_TRANSITIONAL_PA2 */,
    {  793.701, 1190.551} /* HPDF_PAGE_SIZE_TRANSITIONAL_PA3 */,
    {  595.276,  793.701} /* HPDF_PAGE_SIZE_TRANSITIONAL_PA4 */,
    {  396.850,  595.276} /* HPDF_PAGE_SIZE_TRANSITIONAL_PA5 */,
    {  297.638,  396.850} /* HPDF_PAGE_SIZE_TRANSITIONAL_PA6 */,
    {  198.425,  297.638} /* HPDF_PAGE_SIZE_TRANSITIONAL_PA7 */,
    {  147.402,  198.425} /* HPDF_PAGE_SIZE_TRANSITIONAL_PA8 */,
    {   99.213,  147.402} /* HPDF_PAGE_SIZE_TRANSITIONAL_PA9 */,
    {   73.701,   99.213} /* HPDF_PAGE_SIZE_TRANSITIONAL_PA10 */,

    { 2383.937, 3744.567} /* HPDF_PAGE_SIZE_TRANSITIONAL_F0 */,
    { 1870.866, 2383.937} /* HPDF_PAGE_SIZE_TRANSITIONAL_F1 */,
    { 1190.551, 1870.866} /* HPDF_PAGE_SIZE_TRANSITIONAL_F2 */,
    {  935.433, 1190.551} /* HPDF_PAGE_SIZE_TRANSITIONAL_F3 */,
    {  595.276,  935.433} /* HPDF_PAGE_SIZE_TRANSITIONAL_F4 */,
    {  467.717,  595.276} /* HPDF_PAGE_SIZE_TRANSITIONAL_F5 */,
    {  297.638,  467.717} /* HPDF_PAGE_SIZE_TRANSITIONAL_F6 */,
    {  232.441,  297.638} /* HPDF_PAGE_SIZE_TRANSITIONAL_F7 */,
    {  147.402,  232.441} /* HPDF_PAGE_SIZE_TRANSITIONAL_F8 */,
    {  116.220,  147.402} /* HPDF_PAGE_SIZE_TRANSITIONAL_F9 */,
    {   73.701,  116.220} /* HPDF_PAGE_SIZE_TRANSITIONAL_F10 */,

    { 2230.866, 3815.434} /* HPDF_PAGE_SIZE_IMPERIAL_ANTIQUARIAN */,
    { 1870.866, 2449.134} /* HPDF_PAGE_SIZE_IMPERIAL_ATLAS */,
    {  972.284, 1150.866} /* HPDF_PAGE_SIZE_IMPERIAL_BRIEF */,
    { 1295.433, 1729.134} /* HPDF_PAGE_SIZE_IMPERIAL_BROADSHEET */,
    { 1510.866, 1870.866} /* HPDF_PAGE_SIZE_IMPERIAL_CARTRIDGE */,
    { 1692.284, 2483.150} /* HPDF_PAGE_SIZE_IMPERIAL_COLUMBIER */,
    { 1150.866, 1440.000} /* HPDF_PAGE_SIZE_IMPERIAL_COPY_DRAUGHT */,
    { 1080.000, 1440.000} /* HPDF_PAGE_SIZE_IMPERIAL_CROWN */,
    { 1261.417, 1621.418} /* HPDF_PAGE_SIZE_IMPERIAL_DEMY */,
    { 1621.418, 2556.851} /* HPDF_PAGE_SIZE_IMPERIAL_DOUBLE_DEMY */,
    { 2520.000, 3240.000} /* HPDF_PAGE_SIZE_IMPERIAL_QUAD_DEMY */,
    { 1655.433, 2015.433} /* HPDF_PAGE_SIZE_IMPERIAL_ELEPHANT */,
    { 1921.890, 2880.000} /* HPDF_PAGE_SIZE_IMPERIAL_DOUBLE_ELEPHANT */,
    { 3455.433, 5184.568} /* HPDF_PAGE_SIZE_IMPERIAL_EMPEROR */,
    {  972.284, 1224.567} /* HPDF_PAGE_SIZE_IMPERIAL_FOOLSCAP */,
    {  955.276, 1187.717} /* HPDF_PAGE_SIZE_IMPERIAL_SMALL_FOOLSCAP */,
    { 2069.292, 3024.567} /* HPDF_PAGE_SIZE_IMPERIAL_GRAND_EAGLE */,
    { 1584.567, 2160.000} /* HPDF_PAGE_SIZE_IMPERIAL_IMPERIAL */,
    { 1332.284, 1655.433} /* HPDF_PAGE_SIZE_IMPERIAL_MEDIUM */,
    {  521.575,  756.850} /* HPDF_PAGE_SIZE_IMPERIAL_MONARCH */,
    { 1116.851, 1386.142} /* HPDF_PAGE_SIZE_IMPERIAL_POST */,
    { 1403.150, 1692.284} /* HPDF_PAGE_SIZE_IMPERIAL_HALF_POST */,
    { 1062.992, 1332.284} /* HPDF_PAGE_SIZE_IMPERIAL_PINCHED_POST */,
    { 1116.851, 1440.000} /* HPDF_PAGE_SIZE_IMPERIAL_LARGE_POST */,
    { 1510.866, 2375.433} /* HPDF_PAGE_SIZE_IMPERIAL_DOUBLE_LARGE_POST */,
    { 1369.134, 2160.000} /* HPDF_PAGE_SIZE_IMPERIAL_DOUBLE_POST */,
    {  901.417, 1080.000} /* HPDF_PAGE_SIZE_IMPERIAL_POTT */,
    { 1547.717, 2015.433} /* HPDF_PAGE_SIZE_IMPERIAL_PRINCESS */,
    {  649.134,  790.866} /* HPDF_PAGE_SIZE_IMPERIAL_QUARTO */,
    { 1440.000, 1800.000} /* HPDF_PAGE_SIZE_IMPERIAL_ROYAL */,
    { 1369.134, 1944.567} /* HPDF_PAGE_SIZE_IMPERIAL_SUPER_ROYAL */,

    {  850.394, 1133.858} /* HPDF_PAGE_SIZE_FRENCH_CLOCHE */,
    {  878.740, 1133.858} /* HPDF_PAGE_SIZE_FRENCH_POT_ECOLIER */,
    {  963.780, 1247.244} /* HPDF_PAGE_SIZE_FRENCH_TELLIERE */,
    { 1020.473, 1020.473} /* HPDF_PAGE_SIZE_FRENCH_COURONNE_ECRITURE */,
    { 1048.819, 1332.284} /* HPDF_PAGE_SIZE_FRENCH_COURONNE_EDITION */,
    { 1105.512, 1417.323} /* HPDF_PAGE_SIZE_FRENCH_ROBERTO */,
    { 1133.858, 1474.016} /* HPDF_PAGE_SIZE_FRENCH_ECU */,
    { 1247.244, 1587.402} /* HPDF_PAGE_SIZE_FRENCH_COQUILLE */,
    { 1275.591, 1587.402} /* HPDF_PAGE_SIZE_FRENCH_CARRE */,
    { 1303.937, 1757.481} /* HPDF_PAGE_SIZE_FRENCH_CAVALIER */,
    {  921.260, 1417.323} /* HPDF_PAGE_SIZE_FRENCH_DEMI_RAISIN */,
    { 1417.323, 1842.520} /* HPDF_PAGE_SIZE_FRENCH_RAISIN */,
    { 1842.520, 2834.646} /* HPDF_PAGE_SIZE_FRENCH_DOUBLE_RAISIN */,
    { 1587.402, 2154.331} /* HPDF_PAGE_SIZE_FRENCH_JESUS */,
    { 1700.788, 2267.717} /* HPDF_PAGE_SIZE_FRENCH_SOLEIL */,
    { 1700.788, 2267.717} /* HPDF_PAGE_SIZE_FRENCH_COLOMBIER_AFFICHE */,
    { 1785.827, 2551.181} /* HPDF_PAGE_SIZE_FRENCH_COLOMBIER_COMMERCIAL */,
    { 1984.252, 2664.567} /* HPDF_PAGE_SIZE_FRENCH_PETIT_AIGLE */,
    { 2125.985, 2976.378} /* HPDF_PAGE_SIZE_FRENCH_GRAND_AIGLE */,
    { 2551.181, 3571.654} /* HPDF_PAGE_SIZE_FRENCH_GRAND_MONDE */,
    { 2834.646, 3203.150} /* HPDF_PAGE_SIZE_FRENCH_UNIVERS */,

    {  581.102,  822.047} /* HPDF_PAGE_SIZE_RUSSIAN_60X84_8 */,
    {  411.024,  566.929} /* HPDF_PAGE_SIZE_RUSSIAN_60X84_16 */,
    {  283.465,  396.850} /* HPDF_PAGE_SIZE_RUSSIAN_60X84_32 */,
    {  623.622,  822.047} /* HPDF_PAGE_SIZE_RUSSIAN_60X90_8 */,
    {  411.024,  609.449} /* HPDF_PAGE_SIZE_RUSSIAN_60X90_16 */,
    {  481.890,  680.315} /* HPDF_PAGE_SIZE_RUSSIAN_70X100_16 */,
    {  340.158,  467.717} /* HPDF_PAGE_SIZE_RUSSIAN_70X100_32 */,
    {  751.181,  963.780} /* HPDF_PAGE_SIZE_RUSSIAN_70X108_8 */,
    {  481.890,  737.008} /* HPDF_PAGE_SIZE_RUSSIAN_70X108_16 */,
    {  368.504,  467.717} /* HPDF_PAGE_SIZE_RUSSIAN_70X108_32 */,
    {  481.890,  609.449} /* HPDF_PAGE_SIZE_RUSSIAN_70X90_16 */,
    {  303.307,  467.717} /* HPDF_PAGE_SIZE_RUSSIAN_70X90_32 */,
    {  303.307,  501.732} /* HPDF_PAGE_SIZE_RUSSIAN_75X90_32 */,
    {  581.102,  737.008} /* HPDF_PAGE_SIZE_RUSSIAN_84X108_8 */,
    {  368.504,  566.929} /* HPDF_PAGE_SIZE_RUSSIAN_84X108_32 */,

    {    0.000,    0.000} /* HPDF_PAGE_SIZE_EOF */
};

/**
  \ingroup page
  \brief Predefined page size names.
*/
static const char * const HPDF_PREDEFINED_PAGE_SIZE_NAMES[] = {
    "US Loose 'Letter' page size (216.0mm x 279.0mm)",
    "US Loose 'Legal' page size (216.0mm x 356.0mm)",
    "US Loose 'Tabloid' page size (279.0mm x 432.0mm)",
    "US Loose 'Ledger' page size (432.0mm x 279.0mm)",
    "US Loose 'Junior Legal' page size (127.0mm x 203.0mm)",
    "US Loose 'Half Letter' page size (140.0mm x 216.0mm)",
    "US Loose 'Government Letter' page size (203.0mm x 267.0mm)",
    "US Loose 'Government Legal' page size (216.0mm x 330.0mm)",

    "US ANSI 'ANSI A' page size (216.0mm x 279.0mm)",
    "US ANSI 'ANSI B' page size (279.0mm x 432.0mm)",
    "US ANSI 'ANSI C' page size (432.0mm x 559.0mm)",
    "US ANSI 'ANSI D' page size (559.0mm x 864.0mm)",
    "US ANSI 'ANSI E' page size (864.0mm x 1118.0mm)",

    "US Arch 'Arch A' page size (229.0mm x 305.0mm)",
    "US Arch 'Arch B' page size (305.0mm x 457.0mm)",
    "US Arch 'Arch C' page size (457.0mm x 610.0mm)",
    "US Arch 'Arch D' page size (610.0mm x 914.0mm)",
    "US Arch 'Arch E' page size (914.0mm x 1219.0mm)",
    "US Arch 'Arch E1' page size (762.0mm x 1067.0mm)",
    "US Arch 'Arch E2' page size (660.0mm x 965.0mm)",
    "US Arch 'Arch E3' page size (686.0mm x 991.0mm)",

    "ISO 216 '4A0' page size (1682.0mm x 2378.0mm)",
    "ISO 216 '2A0' page size (1189.0mm x 1682.0mm)",
    "ISO 216 'A0' page size (841.0mm x 1189.0mm)",
    "ISO 216 'A0+' page size (914.0mm x 1292.0mm)",
    "ISO 216 'A1' page size (594.0mm x 841.0mm)",
    "ISO 216 'A1+' page size (609.0mm x 914.0mm)",
    "ISO 216 'A2' page size (420.0mm x 594.0mm)",
    "ISO 216 'A3' page size (297.0mm x 420.0mm)",
    "ISO 216 'A3+' page size (329.0mm x 483.0mm)",
    "ISO 216 'A4' page size (210.0mm x 297.0mm)",
    "ISO 216 'A5' page size (148.0mm x 210.0mm)",
    "ISO 216 'A6' page size (105.0mm x 148.0mm)",
    "ISO 216 'A7' page size (74.0mm x 105.0mm)",
    "ISO 216 'A8' page size (52.0mm x 74.0mm)",
    "ISO 216 'A9' page size (37.0mm x 52.0mm)",
    "ISO 216 'A10' page size (26.0mm x 37.0mm)",
    "ISO 216 'B0' page size (1000.0mm x 1414.0mm)",
    "ISO 216 'B0+' page size (1118.0mm x 1580.0mm)",
    "ISO 216 'B1' page size (707.0mm x 1000.0mm)",
    "ISO 216 'B1+' page size (720.0mm x 1020.0mm)",
    "ISO 216 'B2' page size (500.0mm x 707.0mm)",
    "ISO 216 'B2+' page size (520.0mm x 720.0mm)",
    "ISO 216 'B3' page size (353.0mm x 500.0mm)",
    "ISO 216 'B4' page size (250.0mm x 353.0mm)",
    "ISO 216 'B5' page size (176.0mm x 250.0mm)",
    "ISO 216 'B6' page size (125.0mm x 176.0mm)",
    "ISO 216 'B7' page size (88.0mm x 125.0mm)",
    "ISO 216 'B8' page size (62.0mm x 88.0mm)",
    "ISO 216 'B9' page size (44.0mm x 62.0mm)",
    "ISO 216 'B10' page size (31.0mm x 44.0mm)",
    "ISO 216 'B11' page size (22.0mm x 31.0mm)",
    "ISO 216 'B12' page size (15.0mm x 22.0mm)",
    "ISO 216 'B13' page size (11.0mm x 15.0mm)",
    "ISO 216 'C0' page size (917.0mm x 1297.0mm)",
    "ISO 216 'C1' page size (648.0mm x 917.0mm)",
    "ISO 216 'C2' page size (458.0mm x 648.0mm)",
    "ISO 216 'C3' page size (324.0mm x 458.0mm)",
    "ISO 216 'C4' page size (229.0mm x 324.0mm)",
    "ISO 216 'C5' page size (162.0mm x 229.0mm)",
    "ISO 216 'C6' page size (114.0mm x 162.0mm)",
    "ISO 216 'C7' page size (81.0mm x 114.0mm)",
    "ISO 216 'C8' page size (57.0mm x 81.0mm)",
    "ISO 216 'C9' page size (40.0mm x 57.0mm)",
    "ISO 216 'C10' page size (28.0mm x 40.0mm)",

    "Traditional British 'Dukes' page size (140.0mm x 178.0mm)",
    "Traditional British 'Foolscap' page size (203.0mm x 330.0mm)",
    "Traditional British 'Imperial' page size (178.0mm x 229.0mm)",
    "Traditional British 'Kings' page size (165.0mm x 203.0mm)",
    "Traditional British 'Quarto' page size (203.0mm x 254.0mm)",

    "US Commercial envelopes '6¼' page size (152.0mm x 89.0mm)",
    "US Commercial envelopes '6¾' page size (165.0mm x 92.0mm)",
    "US Commercial envelopes '7' page size (172.0mm x 95.0mm)",
    "US Commercial envelopes '7¾ Monarch' page size (191.0mm x 98.0mm)",
    "US Commercial envelopes '8⅝ ' page size (219.0mm x 92.0mm)",
    "US Commercial envelopes '9' page size (225.0mm x 98.0mm)",
    "US Commercial envelopes '10' page size (241.0mm x 104.0mm)",
    "US Commercial envelopes '11' page size (264.0mm x 114.0mm)",
    "US Commercial envelopes '12' page size (279.0mm x 121.0mm)",
    "US Commercial envelopes '14' page size (292.0mm x 127.0mm)",
    "US Commercial envelopes '16' page size (305.0mm x 152.0mm)",

    "US Announcement envelopes 'A1' page size (92.0mm x 130.0mm)",
    "US Announcement envelopes 'A2 Lady Grey' page size (146.0mm x 111.0mm)",
    "US Announcement envelopes 'A4' page size (159.0mm x 108.0mm)",
    "US Announcement envelopes 'A6 Thompson's Standard' page size (165.0mm x 121.0mm)",
    "US Announcement envelopes 'A7 Besselheim' page size (184.0mm x 133.0mm)",
    "US Announcement envelopes 'A8 Carr's' page size (206.0mm x 140.0mm)",
    "US Announcement envelopes 'A9 Diplomat' page size (222.0mm x 146.0mm)",
    "US Announcement envelopes 'A10 Willow' page size (241.0mm x 152.0mm)",
    "US Announcement envelopes 'A Long' page size (225.0mm x 98.0mm)",

    "US Catalog envelopes '1' page size (229.0mm x 152.0mm)",
    "US Catalog envelopes '1¾' page size (241.0mm x 152.0mm)",
    "US Catalog envelopes '3' page size (254.0mm x 178.0mm)",
    "US Catalog envelopes '6' page size (267.0mm x 191.0mm)",
    "US Catalog envelopes '8' page size (286.0mm x 210.0mm)",
    "US Catalog envelopes '9¾' page size (286.0mm x 222.0mm)",
    "US Catalog envelopes '10½' page size (305.0mm x 229.0mm)",
    "US Catalog envelopes '12½' page size (318.0mm x 241.0mm)",
    "US Catalog envelopes '13½' page size (330.0mm x 254.0mm)",
    "US Catalog envelopes '14½' page size (368.0mm x 292.0mm)",
    "US Catalog envelopes '15' page size (381.0mm x 254.0mm)",
    "US Catalog envelopes '15½' page size (394.0mm x 305.0mm)",

    "ISO 269 'DL' page size (110.0mm x 220.0mm)",
    "ISO 269 'B4' page size (250.0mm x 353.0mm)",
    "ISO 269 'B5' page size (176.0mm x 250.0mm)",
    "ISO 269 'B6' page size (125.0mm x 176.0mm)",
    "ISO 269 'C3' page size (324.0mm x 458.0mm)",
    "ISO 269 'C4' page size (229.0mm x 324.0mm)",
    "ISO 269 'C4M' page size (318.0mm x 229.0mm)",
    "ISO 269 'C5' page size (162.0mm x 229.0mm)",
    "ISO 269 'C6/C5' page size (114.0mm x 229.0mm)",
    "ISO 269 'C6' page size (114.0mm x 162.0mm)",
    "ISO 269 'C64M' page size (318.0mm x 114.0mm)",
    "ISO 269 'C7/C6' page size (81.0mm x 162.0mm)",
    "ISO 269 'C7' page size (81.0mm x 114.0mm)",
    "ISO 269 'CE4' page size (229.0mm x 310.0mm)",
    "ISO 269 'CE64' page size (114.0mm x 310.0mm)",
    "ISO 269 'E4' page size (220.0mm x 312.0mm)",
    "ISO 269 'EC45' page size (220.0mm x 229.0mm)",
    "ISO 269 'EC5' page size (155.0mm x 229.0mm)",
    "ISO 269 'E5' page size (115.0mm x 220.0mm)",
    "ISO 269 'E56' page size (155.0mm x 155.0mm)",
    "ISO 269 'E6' page size (110.0mm x 155.0mm)",
    "ISO 269 'E65' page size (110.0mm x 220.0mm)",
    "ISO 269 'R7' page size (120.0mm x 135.0mm)",
    "ISO 269 'S4' page size (250.0mm x 330.0mm)",
    "ISO 269 'S5' page size (185.0mm x 255.0mm)",
    "ISO 269 'S65' page size (110.0mm x 225.0mm)",
    "ISO 269 'X5' page size (105.0mm x 216.0mm)",
    "ISO 269 'EX5' page size (155.0mm x 216.0mm)",

    "Photography 'Passport' page size (35.0mm x 45.0mm)",
    "Photography '2R' page size (64.0mm x 89.0mm)",
    "Photography 'LD' page size (89.0mm x 119.0mm)",
    "Photography 'DSC' page size (89.0mm x 119.0mm)",
    "Photography '3R' page size (89.0mm x 127.0mm)",
    "Photography 'L' page size (89.0mm x 127.0mm)",
    "Photography 'LW' page size (89.0mm x 133.0mm)",
    "Photography 'KGD' page size (102.0mm x 136.0mm)",
    "Photography 'KG' page size (102.0mm x 152.0mm)",
    "Photography '4R' page size (102.0mm x 152.0mm)",
    "Photography '2LD' page size (127.0mm x 169.0mm)",
    "Photography 'DSCW' page size (127.0mm x 169.0mm)",
    "Photography '2L' page size (127.0mm x 178.0mm)",
    "Photography '5R' page size (127.0mm x 178.0mm)",
    "Photography '2LW' page size (127.0mm x 190.0mm)",
    "Photography '6R' page size (152.0mm x 203.0mm)",
    "Photography '8R' page size (203.0mm x 254.0mm)",
    "Photography '6P' page size (203.0mm x 254.0mm)",
    "Photography '6PW' page size (203.0mm x 305.0mm)",
    "Photography 'S8R' page size (203.0mm x 305.0mm)",
    "Photography '11R' page size (279.0mm x 356.0mm)",
    "Photography 'A3+ Super B' page size (330.0mm x 483.0mm)",

    "Newspaper 'Berliner' page size (315.0mm x 470.0mm)",
    "Newspaper 'Broadsheet' page size (597.0mm x 749.0mm)",
    "Newspaper 'US Broadsheet' page size (381.0mm x 578.0mm)",
    "Newspaper 'British Broadsheet' page size (375.0mm x 597.0mm)",
    "Newspaper 'South African Broadsheet' page size (410.0mm x 578.0mm)",
    "Newspaper 'Ciner' page size (350.0mm x 500.0mm)",
    "Newspaper 'Compact' page size (280.0mm x 430.0mm)",
    "Newspaper 'Nordisch' page size (400.0mm x 570.0mm)",
    "Newspaper 'Rhenish' page size (350.0mm x 520.0mm)",
    "Newspaper 'Swiss' page size (320.0mm x 475.0mm)",
    "Newspaper 'Tabloid' page size (280.0mm x 430.0mm)",
    "Newspaper 'Canadian Tabloid' page size (260.0mm x 368.0mm)",
    "Newspaper 'Norwegian Tabloid' page size (280.0mm x 400.0mm)",
    "Newspaper 'New York Times' page size (305.0mm x 559.0mm)",
    "Newspaper 'Wall Street Journal' page size (305.0mm x 578.0mm)",

    "Book 'Folio' page size (304.8mm x 482.6mm)",
    "Book 'Quarto' page size (241.3mm x 304.8mm)",
    "Book 'Imperial Octavo' page size (209.6mm x 292.1mm)",
    "Book 'Super Octavo' page size (177.8mm x 279.4mm)",
    "Book 'Royal Octavo' page size (165.1mm x 254.0mm)",
    "Book 'Medium Octavo' page size (165.1mm x 234.9mm)",
    "Book 'Octavo' page size (152.4mm x 228.6mm)",
    "Book 'Crown Octavo' page size (136.5mm x 203.2mm)",
    "Book '12mo' page size (127.0mm x 187.3mm)",
    "Book '16mo' page size (101.6mm x 171.4mm)",
    "Book '18mo' page size (101.6mm x 165.1mm)",
    "Book '32mo' page size (88.9mm x 139.7mm)",
    "Book '48mo' page size (63.5mm x 101.6mm)",
    "Book '64mo' page size (50.8mm x 76.2mm)",
    "Book 'A Format' page size (110.0mm x 178.0mm)",
    "Book 'B Format' page size (129.0mm x 198.0mm)",
    "Book 'C Format' page size (135.0mm x 216.0mm)",

    "Business Card 'ISO 216' page size (74.0mm x 52.0mm)",
    "Business Card 'US/Canada' page size (88.9mm x 50.8mm)",
    "Business Card 'European' page size (85.0mm x 55.0mm)",
    "Business Card 'Scandinavia' page size (90.0mm x 55.0mm)",
    "Business Card 'China' page size (90.0mm x 54.0mm)",
    "Business Card 'Japan' page size (91.0mm x 55.0mm)",
    "Business Card 'Iran' page size (85.0mm x 48.0mm)",
    "Business Card 'Hungary' page size (90.0mm x 50.0mm)",
    "Business Card 'ISO 7810 ID-1' page size (85.6mm x 54.0mm)",

    "ISO 217:1995 'RA0' page size (860.0mm x 1220.0mm)",
    "ISO 217:1995 'RA1' page size (610.0mm x 860.0mm)",
    "ISO 217:1995 'RA2' page size (430.0mm x 610.0mm)",
    "ISO 217:1995 'RA3' page size (305.0mm x 430.0mm)",
    "ISO 217:1995 'RA4' page size (215.0mm x 305.0mm)",
    "ISO 217:1995 'SRA0' page size (900.0mm x 1280.0mm)",
    "ISO 217:1995 'SRA1' page size (640.0mm x 900.0mm)",
    "ISO 217:1995 'SRA2' page size (450.0mm x 640.0mm)",
    "ISO 217:1995 'SRA3' page size (320.0mm x 450.0mm)",
    "ISO 217:1995 'SRA4' page size (225.0mm x 320.0mm)",
    "ISO 217:1995 'SRA1+' page size (660.0mm x 920.0mm)",
    "ISO 217:1995 'SRA2+' page size (480.0mm x 650.0mm)",
    "ISO 217:1995 'SRA3+' page size (320.0mm x 460.0mm)",
    "ISO 217:1995 'SRA3++' page size (320.0mm x 464.0mm)",
    "ISO 217:1995 'A0U' page size (880.0mm x 1230.0mm)",
    "ISO 217:1995 'A1U' page size (625.0mm x 880.0mm)",
    "ISO 217:1995 'A2U' page size (450.0mm x 625.0mm)",
    "ISO 217:1995 'A3U' page size (330.0mm x 450.0mm)",
    "ISO 217:1995 'A4U' page size (240.0mm x 330.0mm)",

    "Billboard '1 Sheet' page size (508.0mm x 762.0mm)",
    "Billboard '2 Sheet' page size (762.0mm x 1016.0mm)",
    "Billboard '4 Sheet' page size (1016.0mm x 1524.0mm)",
    "Billboard '6 Sheet' page size (1200.0mm x 1800.0mm)",
    "Billboard '12 Sheet' page size (3048.0mm x 1524.0mm)",
    "Billboard '16 Sheet' page size (2032.0mm x 3048.0mm)",
    "Billboard '32 Sheet' page size (4064.0mm x 3048.0mm)",
    "Japanese JIS 'JB0' page size (1030.0mm x 1456.0mm)",
    "Japanese JIS 'JB1' page size (728.0mm x 1030.0mm)",
    "Japanese JIS 'JB2' page size (515.0mm x 728.0mm)",
    "Japanese JIS 'JB3' page size (364.0mm x 515.0mm)",
    "Japanese JIS 'JB4' page size (257.0mm x 364.0mm)",
    "Japanese JIS 'JB5' page size (182.0mm x 257.0mm)",
    "Japanese JIS 'JB6' page size (128.0mm x 182.0mm)",
    "Japanese JIS 'JB7' page size (91.0mm x 128.0mm)",
    "Japanese JIS 'JB8' page size (64.0mm x 91.0mm)",
    "Japanese JIS 'JB9' page size (45.0mm x 64.0mm)",
    "Japanese JIS 'JB10' page size (32.0mm x 45.0mm)",
    "Japanese JIS 'JB11' page size (22.0mm x 32.0mm)",
    "Japanese JIS 'JB12' page size (16.0mm x 22.0mm)",

    "Japanese Shiroku 'Shiroku ban 4' page size (264.0mm x 379.0mm)",
    "Japanese Shiroku 'Shiroku ban 5' page size (189.0mm x 262.0mm)",
    "Japanese Shiroku 'Shiroku ban 6' page size (127.0mm x 188.0mm)",

    "Japanese Kiku 'Kiku 4' page size (227.0mm x 306.0mm)",
    "Japanese Kiku 'Kiku 5' page size (151.0mm x 227.0mm)",

    "Canadian CAN 2-9.60M 'P1' page size (560.0mm x 860.0mm)",
    "Canadian CAN 2-9.60M 'P2' page size (430.0mm x 560.0mm)",
    "Canadian CAN 2-9.60M 'P3' page size (280.0mm x 430.0mm)",
    "Canadian CAN 2-9.60M 'P4' page size (215.0mm x 280.0mm)",
    "Canadian CAN 2-9.60M 'P5' page size (140.0mm x 215.0mm)",
    "Canadian CAN 2-9.60M 'P6' page size (107.0mm x 140.0mm)",

    "German DIN 476 'DIN D0' page size (771.0mm x 1090.0mm)",
    "German DIN 476 'DIN D1' page size (545.0mm x 771.0mm)",
    "German DIN 476 'DIN D2' page size (385.0mm x 545.0mm)",
    "German DIN 476 'DIN D3' page size (272.0mm x 385.0mm)",
    "German DIN 476 'DIN D4' page size (192.0mm x 272.0mm)",
    "German DIN 476 'DIN D5' page size (136.0mm x 192.0mm)",
    "German DIN 476 'DIN D6' page size (96.0mm x 136.0mm)",
    "German DIN 476 'DIN D7' page size (68.0mm x 96.0mm)",
    "German DIN 476 'DIN D8' page size (48.0mm x 68.0mm)",

    "Swedish SIS 01 47 11 'SIS E0' page size (878.0mm x 1242.0mm)",
    "Swedish SIS 01 47 11 'SIS E1' page size (621.0mm x 878.0mm)",
    "Swedish SIS 01 47 11 'SIS E2' page size (439.0mm x 621.0mm)",
    "Swedish SIS 01 47 11 'SIS E3' page size (310.0mm x 439.0mm)",
    "Swedish SIS 01 47 11 'SIS E4' page size (220.0mm x 310.0mm)",
    "Swedish SIS 01 47 11 'SIS E5' page size (155.0mm x 220.0mm)",
    "Swedish SIS 01 47 11 'SIS E6' page size (110.0mm x 155.0mm)",
    "Swedish SIS 01 47 11 'SIS E7' page size (78.0mm x 110.0mm)",
    "Swedish SIS 01 47 11 'SIS E8' page size (55.0mm x 78.0mm)",
    "Swedish SIS 01 47 11 'SIS E9' page size (39.0mm x 55.0mm)",
    "Swedish SIS 01 47 11 'SIS E10' page size (27.0mm x 39.0mm)",
    "Swedish SIS 01 47 11 'SIS F0' page size (958.0mm x 1354.0mm)",
    "Swedish SIS 01 47 11 'SIS F1' page size (677.0mm x 958.0mm)",
    "Swedish SIS 01 47 11 'SIS F2' page size (479.0mm x 677.0mm)",
    "Swedish SIS 01 47 11 'SIS F3' page size (339.0mm x 479.0mm)",
    "Swedish SIS 01 47 11 'SIS F4' page size (239.0mm x 339.0mm)",
    "Swedish SIS 01 47 11 'SIS F5' page size (169.0mm x 239.0mm)",
    "Swedish SIS 01 47 11 'SIS F6' page size (120.0mm x 169.0mm)",
    "Swedish SIS 01 47 11 'SIS F7' page size (85.0mm x 120.0mm)",
    "Swedish SIS 01 47 11 'SIS F8' page size (60.0mm x 85.0mm)",
    "Swedish SIS 01 47 11 'SIS F9' page size (42.0mm x 60.0mm)",
    "Swedish SIS 01 47 11 'SIS F10' page size (30.0mm x 42.0mm)",
    "Swedish SIS 01 47 11 'SIS G0' page size (1044.0mm x 1477.0mm)",
    "Swedish SIS 01 47 11 'SIS G1' page size (738.0mm x 1044.0mm)",
    "Swedish SIS 01 47 11 'SIS G2' page size (522.0mm x 738.0mm)",
    "Swedish SIS 01 47 11 'SIS G3' page size (369.0mm x 522.0mm)",
    "Swedish SIS 01 47 11 'SIS G4' page size (261.0mm x 369.0mm)",
    "Swedish SIS 01 47 11 'SIS G5' page size (185.0mm x 261.0mm)",
    "Swedish SIS 01 47 11 'SIS G6' page size (131.0mm x 185.0mm)",
    "Swedish SIS 01 47 11 'SIS G7' page size (92.0mm x 131.0mm)",
    "Swedish SIS 01 47 11 'SIS G8' page size (65.0mm x 92.0mm)",
    "Swedish SIS 01 47 11 'SIS G9' page size (46.0mm x 65.0mm)",
    "Swedish SIS 01 47 11 'SIS G10' page size (33.0mm x 46.0mm)",
    "Swedish SIS 01 47 11 'SIS D0' page size (1091.0mm x 1542.0mm)",
    "Swedish SIS 01 47 11 'SIS D1' page size (771.0mm x 1091.0mm)",
    "Swedish SIS 01 47 11 'SIS D2' page size (545.0mm x 771.0mm)",
    "Swedish SIS 01 47 11 'SIS D3' page size (386.0mm x 545.0mm)",
    "Swedish SIS 01 47 11 'SIS D4' page size (273.0mm x 386.0mm)",
    "Swedish SIS 01 47 11 'SIS D5' page size (193.0mm x 273.0mm)",
    "Swedish SIS 01 47 11 'SIS D6' page size (136.0mm x 193.0mm)",
    "Swedish SIS 01 47 11 'SIS D7' page size (96.0mm x 136.0mm)",
    "Swedish SIS 01 47 11 'SIS D8' page size (68.0mm x 96.0mm)",
    "Swedish SIS 01 47 11 'SIS D9' page size (48.0mm x 68.0mm)",
    "Swedish SIS 01 47 11 'SIS D10' page size (34.0mm x 48.0mm)",

    "Colombian 'Carta' page size (216.0mm x 279.0mm)",
    "Colombian 'Extra Tabloide' page size (304.0mm x 457.2mm)",
    "Colombian 'Oficio' page size (216.0mm x 330.0mm)",
    "Colombian '1/8 pliego' page size (250.0mm x 350.0mm)",
    "Colombian '1/4 pliego' page size (350.0mm x 500.0mm)",
    "Colombian '1/2 pliego' page size (500.0mm x 700.0mm)",
    "Colombian 'Pliego' page size (700.0mm x 1000.0mm)",

    "Chinese GB/T 148-1997 'D0' page size (764.0mm x 1064.0mm)",
    "Chinese GB/T 148-1997 'D1' page size (532.0mm x 760.0mm)",
    "Chinese GB/T 148-1997 'D2' page size (380.0mm x 528.0mm)",
    "Chinese GB/T 148-1997 'D3' page size (264.0mm x 376.0mm)",
    "Chinese GB/T 148-1997 'D4' page size (188.0mm x 260.0mm)",
    "Chinese GB/T 148-1997 'D5' page size (130.0mm x 184.0mm)",
    "Chinese GB/T 148-1997 'D6' page size (92.0mm x 126.0mm)",
    "Chinese GB/T 148-1997 'RD0' page size (787.0mm x 1092.0mm)",
    "Chinese GB/T 148-1997 'RD1' page size (546.0mm x 787.0mm)",
    "Chinese GB/T 148-1997 'RD2' page size (393.0mm x 546.0mm)",
    "Chinese GB/T 148-1997 'RD3' page size (273.0mm x 393.0mm)",
    "Chinese GB/T 148-1997 'RD4' page size (196.0mm x 273.0mm)",
    "Chinese GB/T 148-1997 'RD5' page size (136.0mm x 196.0mm)",
    "Chinese GB/T 148-1997 'RD6' page size (98.0mm x 136.0mm)",

    "Transitional PA Series 'PA0' page size (840.0mm x 1120.0mm)",
    "Transitional PA Series 'PA1' page size (560.0mm x 840.0mm)",
    "Transitional PA Series 'PA2' page size (420.0mm x 560.0mm)",
    "Transitional PA Series 'PA3' page size (280.0mm x 420.0mm)",
    "Transitional PA Series 'PA4' page size (210.0mm x 280.0mm)",
    "Transitional PA Series 'PA5' page size (140.0mm x 210.0mm)",
    "Transitional PA Series 'PA6' page size (105.0mm x 140.0mm)",
    "Transitional PA Series 'PA7' page size (70.0mm x 105.0mm)",
    "Transitional PA Series 'PA8' page size (52.0mm x 70.0mm)",
    "Transitional PA Series 'PA9' page size (35.0mm x 52.0mm)",
    "Transitional PA Series 'PA10' page size (26.0mm x 35.0mm)",

    "Transitional F Series 'F0' page size (841.0mm x 1321.0mm)",
    "Transitional F Series 'F1' page size (660.0mm x 841.0mm)",
    "Transitional F Series 'F2' page size (420.0mm x 660.0mm)",
    "Transitional F Series 'F3' page size (330.0mm x 420.0mm)",
    "Transitional F Series 'F4' page size (210.0mm x 330.0mm)",
    "Transitional F Series 'F5' page size (165.0mm x 210.0mm)",
    "Transitional F Series 'F6' page size (105.0mm x 165.0mm)",
    "Transitional F Series 'F7' page size (82.0mm x 105.0mm)",
    "Transitional F Series 'F8' page size (52.0mm x 82.0mm)",
    "Transitional F Series 'F9' page size (41.0mm x 52.0mm)",
    "Transitional F Series 'F10' page size (26.0mm x 41.0mm)",

    "Imperial 'Antiquarian' page size (787.0mm x 1346.0mm)",
    "Imperial 'Atlas' page size (660.0mm x 864.0mm)",
    "Imperial 'Brief' page size (343.0mm x 406.0mm)",
    "Imperial 'Broadsheet' page size (457.0mm x 610.0mm)",
    "Imperial 'Cartridge' page size (533.0mm x 660.0mm)",
    "Imperial 'Columbier' page size (597.0mm x 876.0mm)",
    "Imperial 'Copy Draught' page size (406.0mm x 508.0mm)",
    "Imperial 'Crown' page size (381.0mm x 508.0mm)",
    "Imperial 'Demy' page size (445.0mm x 572.0mm)",
    "Imperial 'Double Demy' page size (572.0mm x 902.0mm)",
    "Imperial 'Quad Demy' page size (889.0mm x 1143.0mm)",
    "Imperial 'Elephant' page size (584.0mm x 711.0mm)",
    "Imperial 'Double Elephant' page size (678.0mm x 1016.0mm)",
    "Imperial 'Emperor' page size (1219.0mm x 1829.0mm)",
    "Imperial 'Foolscap' page size (343.0mm x 432.0mm)",
    "Imperial 'Small Foolscap' page size (337.0mm x 419.0mm)",
    "Imperial 'Grand Eagle' page size (730.0mm x 1067.0mm)",
    "Imperial 'Imperial' page size (559.0mm x 762.0mm)",
    "Imperial 'Medium' page size (470.0mm x 584.0mm)",
    "Imperial 'Monarch' page size (184.0mm x 267.0mm)",
    "Imperial 'Post' page size (394.0mm x 489.0mm)",
    "Imperial 'Sheet, Half Post' page size (495.0mm x 597.0mm)",
    "Imperial 'Pinched Post' page size (375.0mm x 470.0mm)",
    "Imperial 'Large Post' page size (394.0mm x 508.0mm)",
    "Imperial 'Double Large Post' page size (533.0mm x 838.0mm)",
    "Imperial 'Double Post' page size (483.0mm x 762.0mm)",
    "Imperial 'Pott' page size (318.0mm x 381.0mm)",
    "Imperial 'Princess' page size (546.0mm x 711.0mm)",
    "Imperial 'Quarto' page size (229.0mm x 279.0mm)",
    "Imperial 'Royal' page size (508.0mm x 635.0mm)",
    "Imperial 'Super Royal' page size (483.0mm x 686.0mm)",

    "French 'Cloche' page size (300.0mm x 400.0mm)",
    "French 'Pot, écolier' page size (310.0mm x 400.0mm)",
    "French 'Tellière' page size (340.0mm x 440.0mm)",
    "French 'Couronne écriture' page size (360.0mm x 360.0mm)",
    "French 'Couronne édition' page size (370.0mm x 470.0mm)",
    "French 'Roberto' page size (390.0mm x 500.0mm)",
    "French 'Écu' page size (400.0mm x 520.0mm)",
    "French 'Coquille' page size (440.0mm x 560.0mm)",
    "French 'Carré' page size (450.0mm x 560.0mm)",
    "French 'Cavalier' page size (460.0mm x 620.0mm)",
    "French 'Demi-raisin' page size (325.0mm x 500.0mm)",
    "French 'Raisin' page size (500.0mm x 650.0mm)",
    "French 'Double Raisin' page size (650.0mm x 1000.0mm)",
    "French 'Jésus' page size (560.0mm x 760.0mm)",
    "French 'Soleil' page size (600.0mm x 800.0mm)",
    "French 'Colombier affiche' page size (600.0mm x 800.0mm)",
    "French 'Colombier commercial' page size (630.0mm x 900.0mm)",
    "French 'Petit Aigle' page size (700.0mm x 940.0mm)",
    "French 'Grand Aigle' page size (750.0mm x 1050.0mm)",
    "French 'Grand Monde' page size (900.0mm x 1260.0mm)",
    "French 'Univers' page size (1000.0mm x 1130.0mm)",

    "Russian GOST 5773-90 '60x84/8' page size (205.0mm x 290.0mm)",
    "Russian GOST 5773-90 '60x84/16' page size (145.0mm x 200.0mm)",
    "Russian GOST 5773-90 '60x84/32' page size (100.0mm x 140.0mm)",
    "Russian GOST 5773-90 '60x90/8' page size (220.0mm x 290.0mm)",
    "Russian GOST 5773-90 '60x90/16' page size (145.0mm x 215.0mm)",
    "Russian GOST 5773-90 '70x100/16' page size (170.0mm x 240.0mm)",
    "Russian GOST 5773-90 '70x100/32' page size (120.0mm x 165.0mm)",
    "Russian GOST 5773-90 '70x108/8' page size (265.0mm x 340.0mm)",
    "Russian GOST 5773-90 '70x108/16' page size (170.0mm x 260.0mm)",
    "Russian GOST 5773-90 '70x108/32' page size (130.0mm x 165.0mm)",
    "Russian GOST 5773-90 '70x90/16' page size (170.0mm x 215.0mm)",
    "Russian GOST 5773-90 '70x90/32' page size (107.0mm x 165.0mm)",
    "Russian GOST 5773-90 '75x90/32' page size (107.0mm x 177.0mm)",
    "Russian GOST 5773-90 '84x108/16' page size (205.0mm x 260.0mm)",
    "Russian GOST 5773-90 '84x108/32' page size (130.0mm x 200.0mm)",

    "Unknown"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _HPDF_PAGE_SIZES_H */

