//
// This file is autogenerated.
// Edit `data/hpdf_page_sizes.template` and `data/hpdf_page_sizes.json` instead.
//

/*
 * << Haru Free PDF Library >> -- hpdf_page_sizes.h
 *
 * URL: http://libharu.org
 *
 * Copyright (c) 1999-2006 Takeshi Kanno <takeshi_kanno@est.hi-ho.ne.jp>
 * Copyright (c) 2007-2009 Antony Dovgal <tony@daylessday.org>
 * Copyright (c) 2023 Dmitry Solomennikov
 *
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.
 * It is provided "as is" without express or implied warranty.
 *
 */

#ifndef _HPDF_PAGE_SIZES_H
#define _HPDF_PAGE_SIZES_H

#ifdef __cplusplus
extern "C" {
#endif

/**
  \ingroup page
  \brief Data structure representing page size (width and height), in points.
*/
typedef struct _HPDF_PageSizeValue {
    HPDF_REAL   x;
    HPDF_REAL   y;
} HPDF_PageSizeValue;

/**
  List of predefined page sizes.

  Data gathered from wonderful site <a href="https://papersizes.io/">https://papersizes.io/</a>

  \image html img/papersizes_logo_small.png

  Known page sizes include:
  - International

  Sizes are given in millimeters and converted to points.
*/
typedef enum _HPDF_PageSizes {
    /// ISO 216 "4A0" page size (1682.0mm x 2378.0mm)
    HPDF_PAGE_SIZE_4A0 = 0,
    /// ISO 216 "2A0" page size (1189.0mm x 1682.0mm)
    HPDF_PAGE_SIZE_2A0,
    /// ISO 216 "A0" page size (841.0mm x 1189.0mm)
    HPDF_PAGE_SIZE_A0,
    /// ISO 216 "A0+" page size (914.0mm x 1292.0mm)
    HPDF_PAGE_SIZE_A0_PLUS,
    /// ISO 216 "A1" page size (594.0mm x 841.0mm)
    HPDF_PAGE_SIZE_A1,
    /// ISO 216 "A1+" page size (609.0mm x 914.0mm)
    HPDF_PAGE_SIZE_A1_PLUS,
    /// ISO 216 "A2" page size (420.0mm x 594.0mm)
    HPDF_PAGE_SIZE_A2,
    /// ISO 216 "A3" page size (297.0mm x 420.0mm)
    HPDF_PAGE_SIZE_A3,
    /// ISO 216 "A3+" page size (329.0mm x 483.0mm)
    HPDF_PAGE_SIZE_A3_PLUS,
    /// ISO 216 "A4" page size (210.0mm x 297.0mm)
    HPDF_PAGE_SIZE_A4,
    /// ISO 216 "A5" page size (148.0mm x 210.0mm)
    HPDF_PAGE_SIZE_A5,
    /// ISO 216 "A6" page size (105.0mm x 148.0mm)
    HPDF_PAGE_SIZE_A6,
    /// ISO 216 "A7" page size (74.0mm x 105.0mm)
    HPDF_PAGE_SIZE_A7,
    /// ISO 216 "A8" page size (52.0mm x 74.0mm)
    HPDF_PAGE_SIZE_A8,
    /// ISO 216 "A9" page size (37.0mm x 52.0mm)
    HPDF_PAGE_SIZE_A9,
    /// ISO 216 "A10" page size (26.0mm x 37.0mm)
    HPDF_PAGE_SIZE_A10,
    /// ISO 216 "B0" page size (1000.0mm x 1414.0mm)
    HPDF_PAGE_SIZE_B0,
    /// ISO 216 "B0+" page size (1118.0mm x 1580.0mm)
    HPDF_PAGE_SIZE_B0_PLUS,
    /// ISO 216 "B1" page size (707.0mm x 1000.0mm)
    HPDF_PAGE_SIZE_B1,
    /// ISO 216 "B1+" page size (720.0mm x 1020.0mm)
    HPDF_PAGE_SIZE_B1_PLUS,
    /// ISO 216 "B2" page size (500.0mm x 707.0mm)
    HPDF_PAGE_SIZE_B2,
    /// ISO 216 "B2+" page size (520.0mm x 720.0mm)
    HPDF_PAGE_SIZE_B2_PLUS,
    /// ISO 216 "B3" page size (353.0mm x 500.0mm)
    HPDF_PAGE_SIZE_B3,
    /// ISO 216 "B4" page size (250.0mm x 353.0mm)
    HPDF_PAGE_SIZE_B4,
    /// ISO 216 "B5" page size (176.0mm x 250.0mm)
    HPDF_PAGE_SIZE_B5,
    /// ISO 216 "B6" page size (125.0mm x 176.0mm)
    HPDF_PAGE_SIZE_B6,
    /// ISO 216 "B7" page size (88.0mm x 125.0mm)
    HPDF_PAGE_SIZE_B7,
    /// ISO 216 "B8" page size (62.0mm x 88.0mm)
    HPDF_PAGE_SIZE_B8,
    /// ISO 216 "B9" page size (44.0mm x 62.0mm)
    HPDF_PAGE_SIZE_B9,
    /// ISO 216 "B10" page size (31.0mm x 44.0mm)
    HPDF_PAGE_SIZE_B10,
    /// ISO 216 "B11" page size (22.0mm x 31.0mm)
    HPDF_PAGE_SIZE_B11,
    /// ISO 216 "B12" page size (15.0mm x 22.0mm)
    HPDF_PAGE_SIZE_B12,
    /// ISO 216 "B13" page size (11.0mm x 15.0mm)
    HPDF_PAGE_SIZE_B13,
    /// ISO 216 "C0" page size (917.0mm x 1297.0mm)
    HPDF_PAGE_SIZE_C0,
    /// ISO 216 "C1" page size (648.0mm x 917.0mm)
    HPDF_PAGE_SIZE_C1,
    /// ISO 216 "C2" page size (458.0mm x 648.0mm)
    HPDF_PAGE_SIZE_C2,
    /// ISO 216 "C3" page size (324.0mm x 458.0mm)
    HPDF_PAGE_SIZE_C3,
    /// ISO 216 "C4" page size (229.0mm x 324.0mm)
    HPDF_PAGE_SIZE_C4,
    /// ISO 216 "C5" page size (162.0mm x 229.0mm)
    HPDF_PAGE_SIZE_C5,
    /// ISO 216 "C6" page size (114.0mm x 162.0mm)
    HPDF_PAGE_SIZE_C6,
    /// ISO 216 "C7" page size (81.0mm x 114.0mm)
    HPDF_PAGE_SIZE_C7,
    /// ISO 216 "C8" page size (57.0mm x 81.0mm)
    HPDF_PAGE_SIZE_C8,
    /// ISO 216 "C9" page size (40.0mm x 57.0mm)
    HPDF_PAGE_SIZE_C9,
    /// ISO 216 "C10" page size (28.0mm x 40.0mm)
    HPDF_PAGE_SIZE_C10,

    /// Last page size enum value
    HPDF_PAGE_SIZE_EOF
} HPDF_PageSizes;

/**
  \ingroup page
  \brief Predefined page sizes (in points).
*/
static const HPDF_PageSizeValue HPDF_PREDEFINED_PAGE_SIZES[] = {
    { 4767.875, 6740.788} /* HPDF_PAGE_SIZE_4A0 */,
    { 3370.394, 4767.875} /* HPDF_PAGE_SIZE_2A0 */,
    { 2383.937, 3370.394} /* HPDF_PAGE_SIZE_A0 */,
    { 2590.866, 3662.363} /* HPDF_PAGE_SIZE_A0_PLUS */,
    { 1683.780, 2383.937} /* HPDF_PAGE_SIZE_A1 */,
    { 1726.299, 2590.866} /* HPDF_PAGE_SIZE_A1_PLUS */,
    { 1190.551, 1683.780} /* HPDF_PAGE_SIZE_A2 */,
    {  841.890, 1190.551} /* HPDF_PAGE_SIZE_A3 */,
    {  932.599, 1369.134} /* HPDF_PAGE_SIZE_A3_PLUS */,
    {  595.276,  841.890} /* HPDF_PAGE_SIZE_A4 */,
    {  419.528,  595.276} /* HPDF_PAGE_SIZE_A5 */,
    {  297.638,  419.528} /* HPDF_PAGE_SIZE_A6 */,
    {  209.764,  297.638} /* HPDF_PAGE_SIZE_A7 */,
    {  147.402,  209.764} /* HPDF_PAGE_SIZE_A8 */,
    {  104.882,  147.402} /* HPDF_PAGE_SIZE_A9 */,
    {   73.701,  104.882} /* HPDF_PAGE_SIZE_A10 */,
    { 2834.646, 4008.189} /* HPDF_PAGE_SIZE_B0 */,
    { 3169.134, 4478.741} /* HPDF_PAGE_SIZE_B0_PLUS */,
    { 2004.095, 2834.646} /* HPDF_PAGE_SIZE_B1 */,
    { 2040.945, 2891.339} /* HPDF_PAGE_SIZE_B1_PLUS */,
    { 1417.323, 2004.095} /* HPDF_PAGE_SIZE_B2 */,
    { 1474.016, 2040.945} /* HPDF_PAGE_SIZE_B2_PLUS */,
    { 1000.630, 1417.323} /* HPDF_PAGE_SIZE_B3 */,
    {  708.662, 1000.630} /* HPDF_PAGE_SIZE_B4 */,
    {  498.898,  708.662} /* HPDF_PAGE_SIZE_B5 */,
    {  354.331,  498.898} /* HPDF_PAGE_SIZE_B6 */,
    {  249.449,  354.331} /* HPDF_PAGE_SIZE_B7 */,
    {  175.748,  249.449} /* HPDF_PAGE_SIZE_B8 */,
    {  124.724,  175.748} /* HPDF_PAGE_SIZE_B9 */,
    {   87.874,  124.724} /* HPDF_PAGE_SIZE_B10 */,
    {   62.362,   87.874} /* HPDF_PAGE_SIZE_B11 */,
    {   42.520,   62.362} /* HPDF_PAGE_SIZE_B12 */,
    {   31.181,   42.520} /* HPDF_PAGE_SIZE_B13 */,
    { 2599.370, 3676.536} /* HPDF_PAGE_SIZE_C0 */,
    { 1836.851, 2599.370} /* HPDF_PAGE_SIZE_C1 */,
    { 1298.268, 1836.851} /* HPDF_PAGE_SIZE_C2 */,
    {  918.425, 1298.268} /* HPDF_PAGE_SIZE_C3 */,
    {  649.134,  918.425} /* HPDF_PAGE_SIZE_C4 */,
    {  459.213,  649.134} /* HPDF_PAGE_SIZE_C5 */,
    {  323.150,  459.213} /* HPDF_PAGE_SIZE_C6 */,
    {  229.606,  323.150} /* HPDF_PAGE_SIZE_C7 */,
    {  161.575,  229.606} /* HPDF_PAGE_SIZE_C8 */,
    {  113.386,  161.575} /* HPDF_PAGE_SIZE_C9 */,
    {   79.370,  113.386} /* HPDF_PAGE_SIZE_C10 */,

    {    0.000,    0.000} /* HPDF_PAGE_SIZE_EOF */
};

/**
  \ingroup page
  \brief Predefined page size names.
*/
static const char * const HPDF_PREDEFINED_PAGE_SIZE_NAMES[] = {
    "ISO 216 '4A0' page size (1682.0mm x 2378.0mm)",
    "ISO 216 '2A0' page size (1189.0mm x 1682.0mm)",
    "ISO 216 'A0' page size (841.0mm x 1189.0mm)",
    "ISO 216 'A0+' page size (914.0mm x 1292.0mm)",
    "ISO 216 'A1' page size (594.0mm x 841.0mm)",
    "ISO 216 'A1+' page size (609.0mm x 914.0mm)",
    "ISO 216 'A2' page size (420.0mm x 594.0mm)",
    "ISO 216 'A3' page size (297.0mm x 420.0mm)",
    "ISO 216 'A3+' page size (329.0mm x 483.0mm)",
    "ISO 216 'A4' page size (210.0mm x 297.0mm)",
    "ISO 216 'A5' page size (148.0mm x 210.0mm)",
    "ISO 216 'A6' page size (105.0mm x 148.0mm)",
    "ISO 216 'A7' page size (74.0mm x 105.0mm)",
    "ISO 216 'A8' page size (52.0mm x 74.0mm)",
    "ISO 216 'A9' page size (37.0mm x 52.0mm)",
    "ISO 216 'A10' page size (26.0mm x 37.0mm)",
    "ISO 216 'B0' page size (1000.0mm x 1414.0mm)",
    "ISO 216 'B0+' page size (1118.0mm x 1580.0mm)",
    "ISO 216 'B1' page size (707.0mm x 1000.0mm)",
    "ISO 216 'B1+' page size (720.0mm x 1020.0mm)",
    "ISO 216 'B2' page size (500.0mm x 707.0mm)",
    "ISO 216 'B2+' page size (520.0mm x 720.0mm)",
    "ISO 216 'B3' page size (353.0mm x 500.0mm)",
    "ISO 216 'B4' page size (250.0mm x 353.0mm)",
    "ISO 216 'B5' page size (176.0mm x 250.0mm)",
    "ISO 216 'B6' page size (125.0mm x 176.0mm)",
    "ISO 216 'B7' page size (88.0mm x 125.0mm)",
    "ISO 216 'B8' page size (62.0mm x 88.0mm)",
    "ISO 216 'B9' page size (44.0mm x 62.0mm)",
    "ISO 216 'B10' page size (31.0mm x 44.0mm)",
    "ISO 216 'B11' page size (22.0mm x 31.0mm)",
    "ISO 216 'B12' page size (15.0mm x 22.0mm)",
    "ISO 216 'B13' page size (11.0mm x 15.0mm)",
    "ISO 216 'C0' page size (917.0mm x 1297.0mm)",
    "ISO 216 'C1' page size (648.0mm x 917.0mm)",
    "ISO 216 'C2' page size (458.0mm x 648.0mm)",
    "ISO 216 'C3' page size (324.0mm x 458.0mm)",
    "ISO 216 'C4' page size (229.0mm x 324.0mm)",
    "ISO 216 'C5' page size (162.0mm x 229.0mm)",
    "ISO 216 'C6' page size (114.0mm x 162.0mm)",
    "ISO 216 'C7' page size (81.0mm x 114.0mm)",
    "ISO 216 'C8' page size (57.0mm x 81.0mm)",
    "ISO 216 'C9' page size (40.0mm x 57.0mm)",
    "ISO 216 'C10' page size (28.0mm x 40.0mm)",

    "Unknown"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _HPDF_PAGE_SIZES_H */

