#define HPDF_MAJOR_VERSION @PROJECT_VERSION_MAJOR@
#define HPDF_MINOR_VERSION @PROJECT_VERSION_MINOR@
#define HPDF_BUGFIX_VERSION @PROJECT_VERSION_PATCH@
#define HPDF_EXTRA_VERSION "@PROJECT_VERSION_EXTRA@"
#define HPDF_VERSION_TEXT "@PROJECT_VERSION_TEXT@"
#define HPDF_VERSION_ID @PROJECT_VERSION_ID@
