/* automatically generated by configure */
/* edit configure.in to change version number */
#define HPDF_MAJOR_VERSION 2
#define HPDF_MINOR_VERSION 3
#define HPDF_BUGFIX_VERSION 0
#define HPDF_EXTRA_VERSION "1-dev"
#define HPDF_VERSION_TEXT "2.3.01-dev"
#define HPDF_VERSION_ID 20300
